### ISSUE TITLE
Add mockup pages for high-level view of the app

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#103]
# 🧱 Description

Along with the flow of UI mockups within the user scenarios, we should have a page dedicated to mock UIs.

## 📋 Acceptance Criteria

- [ ] There is a Wiki page dedicated to the UI mockups.

**Comment by umitcan07** [comment]
We have created the relevant [page](https://github.com/bounswe/bounswe2024group11/wiki/Mockup-Screens).

**Comment by ArdaVural** [comment]
UI mockups are looking pretty clean. 👍
