### ISSUE TITLE
Create a Figma Workspace and invite each group member

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#104]
# 🧱 Description

We will use Figma for our all design purposes. It's a collaborative tool with a generous free tier option. Anything related UI/UX can be done with ease with it. But in order to work efficiently, it's good to have a team in Figma and manage designs thereby. 

The first thing to have in the Figma team is the mockup screens.

Note that we should use the `@std.bogazici.edu.tr` emails to create a student team. 

Please refer to [Mail Addresses Wiki Page](https://github.com/bounswe/bounswe2024group11/wiki/Member-Mail-Adresses)

## 📋 Acceptance Criteria

- [x] The group has a Figma team and project.

**Comment by umitcan07** [comment]
<img width="524" alt="Screenshot 2024-03-17 at 18 08 05" src="https://github.com/bounswe/bounswe2024group11/assets/68506701/206bada1-1f57-4392-9e31-808fa9cbf556">

Comma-separated values rock!

**Comment by umitcan07** [comment]
Invited everyone, and added our mockup designs to the project. It should be good to go

**Comment by Meminseeker** [comment]
Thanks! We're on the group team on the Figma. It is a very versatile tool. Actually, I'm shocked when I see what it can do.
