### ISSUE TITLE
Update Emre's Personal Efforts Page

### ISSUE THREAD

**Issue by tenacke** [bounswe/bounswe2024group11#105]
# 🧱 Description

Update Emre's personal efforts page so that it follows the rules presented in Customer Milestone 1.

Examples:
Poor examples: "I attended the lectures and group meetings" or "I designed a project plan".
Good example: "Researched the Swagger API Development support tools with (another team member) and prepared the infrastructure. The resulting API documentation can be seen at (URI of your API documentation). "

## 📋 Acceptance Criteria

- [x] Emre's personal efforts page reflects the work done by him and abides by the rules.

**Comment by MucahitErdoganUnlu** [comment]
Good job!
