### ISSUE TITLE
Get landing page (_Home) up to date

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#106]
# 🧱 Description

We have made quite a progress since we last updated our landing page, most significantly Milestone 1 related work.
We should update our home page to incorporate changes: 

- Our domain
- Our App details (logo, name, position)
- Requirements (link)
- Brief Project plan and link to the Project Plan Page
- User Scenarios (link)
- Mockups (link)

To be reviewed by @ozankrkya

## 📋 Acceptance Criteria

- [x] All of the aforementioned changes are reflected in the Wiki Home Page

**Comment by ArdaVural** [comment]
Landing page updated and new information about the project is added.

**Comment by umitcan07** [comment]
thanks @ArdaVural it's looking better now! I have slightly changed the formatting and styles.
If we get a review from Ozan as well, we are good to go

**Comment by ozankrkya** [comment]
Very good job guys! I have finished my review on landing page. I have fixed few typos, that's all. 
I am closing this issue since landing page has its current final form.
