### ISSUE TITLE
Report progress for the first Milestone.

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#107]
# 🧱 Description

As a deliverable, we should have a "Milestone 1 Report" page on Wiki.
It should include our progress, project artifacts, etc.

---

### Executive Summary:

- Summary of project and overall status
- List the status of deliverables
- Decisions and choices you have made and your assessment regarding them. These include, but are not limited to, conventions and choices related to issue management, meetings, and wiki documentation)
- Challenges you have met as a group (if any), and how you have or plan to overcome them

### Project plan (Project Libre or GitHub Roadmap.)

Milestones and known tasks must be defined. Plans will be revised as needed.

### RAM

A table that provides a brief and clear summary of work done by each team member. Each member should write their own contributions. HINT:

- Poor examples: “I attended the lectures and group meetings” or “I designed a project plan”.

- Good example: “Researched the Swagger API Development support tools with <X> (another team member) and prepared the infrastructure. The resulting API documentation can be seen at <URI> (URI of your API documentation). ”

### Evaluation of tools and processes you have used to manage your team project. 
This is a lesson learned from the project development decisions made so far – how effectively are the tools being utilized & what changes (if any) are needed as you move forward?

> Please refer to:
[Cmpe352_Customer_Milestone_1.pdf](https://github.com/bounswe/bounswe2024group11/files/14627966/Cmpe352_Customer_Milestone_1.2.pdf)

---

To be reviewed by: @umitcan07, @Meminseeker, @tenacke

The creation of this document is rather crucial, since we will be uploading this directly to Moodle so any other review is highly appreciated and encouraged.

## 📋 Acceptance Criteria

- [ ] There is a Wiki page called "Milestone 1 Report" that includes our progress so far, relevant links, and everything else mentioned in the PDF file.

**Comment by umitcan07** [comment]
Please at least initialize this document as soon as possible so we can iterate over it.

**Comment by MucahitErdoganUnlu** [comment]
created the page [here](https://github.com/bounswe/bounswe2024group11/wiki/Customer-Milestone-1-Report)

**Comment by umitcan07** [comment]
I have created and outlined and populated some of the content

**Comment by umitcan07** [comment]
I have added a personal efforts table template, now you can add your contributions in the same form as mines.
Please make sure to only include what can count as an artifact. Add your research issues if you have contributed to the relevant Wiki page.

**Comment by umitcan07** [comment]
<img width="1920" alt="Milestone #1" src="https://github.com/bounswe/bounswe2024group11/assets/68506701/812c36dc-d4c4-4403-bdc5-6184e2eb0efa">

Designed this cover image, hope it motivates us

**Comment by MucahitErdoganUnlu** [comment]
the report is completed and delivered [here](https://github.com/bounswe/bounswe2024group11/wiki/Customer-Milestone-1-Report).
