### ISSUE TITLE
Update Hasan's Personal Efforts Page

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#109]
# 🧱 Description

Update Hasan's personal efforts page so that it follows the rules presented in Customer Milestone 1.

Examples:
Poor examples: "I attended the lectures and group meetings" or "I designed a project plan".
Good example: "Researched the Swagger API Development support tools with (another team member) and prepared the infrastructure. The resulting API documentation can be seen at (URI of your API documentation). "

## 📋 Acceptance Criteria

- [x] Hasan's personal efforts page reflects the work done by him and abides by the rules.

**Comment by hks1444** [comment]
@MucahitErdoganUnlu can you review this issue?

**Comment by MucahitErdoganUnlu** [comment]
good job!

**Comment by hks1444** [comment]
Scenario 2 is updated to accommodate the change. The picture of [this link](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-2#search--bookmark) is going to be changed.

**Comment by hks1444** [comment]
Oops, sorry that was a funny one. It should have been a comment for #116
