### ISSUE TITLE
Update Muhammed Emin's Personal Efforts Page

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#110]
# 🧱 Description

Update Muhammed Emin's personal efforts page so that it follows the rules presented in Customer Milestone 1.
Also, add any missing week's efforts.

Examples:
Poor examples: "I attended the lectures and group meetings" or "I designed a project plan".
Good example: "Researched the Swagger API Development support tools with (another team member) and prepared the infrastructure. The resulting API documentation can be seen at (URI of your API documentation). "

## 📋 Acceptance Criteria

- [x] There is an efforts table for each week.
- [x]  Muhammed Emin's personal efforts page reflects the work done by him and abides by the rules.

**Comment by Meminseeker** [comment]
I documented my efforts. Here is [my personal efforts page](https://github.com/bounswe/bounswe2024group11/wiki/Personal-Effort-(Muhammed-Emin-Aray%C4%B1c%C4%B1)).

**Comment by tenacke** [comment]
Looks nice!
