### ISSUE TITLE
Update RAM according to Muhammed Emin's responsibilities

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#111]
# 🧱 Description

The[ Responsibility Assignment Matrix (RAM)](https://github.com/bounswe/bounswe2024group11/wiki/Responsibility-Assignment-Matrix) should reflect [Muhammed Emin's Personal Efforts](https://github.com/bounswe/bounswe2024group11/wiki/Personal-Effort-(Muhammed-Emin-Aray%C4%B1c%C4%B1))

## 📋 Acceptance Criteria

- [x]  RAM includes Muhammed Emin's work.

**Comment by Meminseeker** [comment]
I added my tasks to the RAM document even though most of them were put by my colleagues. I also edited some previous marks referring to me.

**Comment by tenacke** [comment]
Looks nice!
