### ISSUE TITLE
Learn SPARQL to query Wikidata (Muhammed Emin Arayıcı)

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#112]
# 🧱 Description

Learn SparQL using [SPARQL tutorial](https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial)

## 📋 Acceptance Criteria

- [ ] Learned how to write basic queries.
- [ ] The tutorial page is read carefully.

**Comment by hks1444** [comment]
Zenith Project is completed last semester.
I am closing this issue since we have started to develop a new project from now on.
