### ISSUE TITLE
Specify design decisions for desktop mockups

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#114]
# 🧱 Description

We only have desktop mockup screens for the first milestone, but it is expected that our customers can at least extrapolate for mobile screens. So we should have a section dedicated to design decisions to express what was on our minds while designing "mobile-first UI design".

## 📋 Acceptance Criteria

- [x] There is a section for mobile screens and design decisions in mockups.

**Comment by Meminseeker** [comment]
There is a priority label missing for this issue. Can you add an appropriate one? So that we can understand how urgent it is and keep track accordingly.

**Comment by umitcan07** [comment]
I have added the relevant section [here](https://github.com/bounswe/bounswe2024group11/wiki/Mockup-Screens) at the bottom.

**Comment by hks1444** [comment]
Looks good to me
