### ISSUE TITLE
Update ProjectLibre Planning According to the Guideline

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#115]
# 🧱 Description

Current version of our project planning in ProjectLibre does not have the desired properties. The tasks that will be done for sure (ie. registration, follow etc) should be indicated in the plan. Optional tasks need not be indicated. (ie. add only the tasks that are described in the assignment). You can use shall requirements (not should) in the [requirements](https://github.com/bounswe/bounswe2024group11/wiki/Requirements) as your guideline.

**Comment by MucahitErdoganUnlu** [comment]
Did you add the project file as indicated by TA:

Ozan Oytun Karakaya — 
How should we add the ProjectLibre file for sharing our project plan in Milestone 1?
Furkan — 
You can export it as a project and put the project file in your repository

**Comment by MucahitErdoganUnlu** [comment]
After that, we can include the link to the page in the report.

**Comment by ozankrkya** [comment]
I re-uploaded screenshots of project plan charts in wiki page and I added the link to [ProjectLibre file](https://drive.google.com/file/d/1xleMHeXdIUpA67wxehXns0ixfnptn3kM/view?usp=drive_link) in wiki.
