### ISSUE TITLE
Add Wikidata Related Scenario

### ISSUE THREAD

**Issue by tenacke** [bounswe/bounswe2024group11#116]
# 🧱 Description

Using Wikidata API is a requirement, so we need to add Wikidata-related stories to our scenarios.

## 📋 Acceptance Criteria

- [ ] At least one scenario is updated and contains usage of Wikidata.

**Comment by MucahitErdoganUnlu** [comment]
This issue is related to [upgrade mockup](https://github.com/bounswe/bounswe2024group11/issues/117)

**Comment by umitcan07** [comment]
@MucahitErdoganUnlu Just a heads up, you can use the sign # to link issues.

**Comment by MucahitErdoganUnlu** [comment]
Thank you!

**Comment by ceydanursen** [comment]
Scenario 2 is updated to add Wikidata-related stories. [Scenario 2](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-2)

**Comment by Meminseeker** [comment]
It looks good for now. But it would be safer to wait for the revisions of the mock-ups to close this issue. Thanks in advance!

**Comment by umitcan07** [comment]
I have reviewed the changes made by you guys, modified the screens accordingly. They now go hand in hand, incorporating semantic search as well!

Congrats ✨
