### ISSUE TITLE
Add Wikidata Metadata Table to Mockups

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#117]
# 🧱 Description
We use Wikidata API to provide metadata about search queries. This should be added in search results page in a mockup.

## 📋 Acceptance Criteria

- [x] A mockup is updated so that it has metadata table in its search results page.

**Comment by tenacke** [comment]
This issue is related to #116.

**Comment by umitcan07** [comment]
<img width="859" alt="Screenshot 2024-03-18 at 17 28 15" src="https://github.com/bounswe/bounswe2024group11/assets/68506701/af8ce940-e756-47f2-9a47-d27754cc98e0">

I have added a semantic Info box, as well as search being smart enough to understand it was Spider-Man that was sought.

Last but not least, I have added a pointer cursor to each screen for a better visibility on the flow.

**Comment by hks1444** [comment]
It clearly shows that the search is semantic. It is well-designed and the cursor shows what is clicked on.

**Comment by hks1444** [comment]
Can you add these to the flows?

**Comment by umitcan07** [comment]
<img width="967" alt="Screenshot 2024-03-18 at 17 37 18" src="https://github.com/bounswe/bounswe2024group11/assets/68506701/d67e2f3e-6082-4720-bf80-d7c830141242">

@Meminseeker The screens are ready to be exported on Figma, can you export them all and update the user scenarios.

**Comment by Meminseeker** [comment]
I looked at the updated mock-up screens, they're amazing. Let's create a new issue to replace all of the mock-ups with the updated ones in Figma because this issue is all about semantic search.
