### ISSUE TITLE
Update RAM according to Hasan's responsibilities

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#121]
# 🧱 Description

The[ Responsibility Assignment Matrix (RAM)](https://github.com/bounswe/bounswe2024group11/wiki/Responsibility-Assignment-Matrix) should reflect [Hasan's Personal Efforts](https://github.com/bounswe/bounswe2024group11/wiki/Personal-Effort-(Hasan-Kerem-%C5%9Eeker))

## 📋 Acceptance Criteria

- [x] RAM includes Hasan's work.

**Comment by umitcan07** [comment]
Reviewed both pages, they look decent after the changes. ✨
