### ISSUE TITLE
Update mock-up screens in all scenario pages

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#123]
# 🧱 Description

All mock-up screens are updated, so the ones in the wiki are outdated now. Update the mock-up screens with fresh ones from [Figma](https://www.figma.com/file/BefZiYhQw14Bo1euCuhyBh/Mockups?type=design&node-id=0-1&mode=design&t=bfMYEtfKfq7bQU3m-0). 

## 📋 Acceptance Criteria

- [x] [Scenario 1](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-1) has updated desktop mock-up screens.
- [x] [Scenario 2](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-2) has updated desktop mock-up screens.
- [x] [Scenario 3](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-3) has updated desktop mock-up screens.
- [x] [Scenario 4](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-4) has updated desktop mock-up screens.
- [x] [Scenario 5](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-5) has updated desktop mock-up screens.

**Comment by Meminseeker** [comment]
I have updated all desktop mock-up screens for all scenarios. You can check them by the links from the description of this issue.

**Comment by MucahitErdoganUnlu** [comment]
Well done!
