### ISSUE TITLE
Update the ProjectLibre Planning 

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#125]
# 🧱 Description

Update the ProjectlLibre file in the Wiki and charts in [project planning](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan)

## 📋 Acceptance Criteria

- [x] ProjectLibre file is changed according to the discussion in the lecture.

**Comment by MucahitErdoganUnlu** [comment]
the file can be accessed [here](https://github.com/bounswe/bounswe2024group11/blob/main/Zenith_Project_Plan.pod)
