### ISSUE TITLE
Draw use case diagrams

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#127]
# 🧱 Description

For the second milestone, we need to have use-case diagrams of the application

## 📋 Acceptance Criteria

- [x] All use cases are determined
- [x] Each use case is drawn
- [x] Each use case is documented
- [x] All use case diagrams and their documentations are in the wiki

**Comment by tenacke** [comment]
The use cases are completed so this issue can be closed. Well done!
