### ISSUE TITLE
Learn the fundamentals of use-case diagrams (Muhammed Emin Arayıcı)

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#128]
# 🧱 Description

Learn what you need to know to draw use case diagrams and how to do it.

## 📋 Acceptance Criteria

- [x] Learn what to do step-by-step for drawing a use-case diagram
- [x] In the wiki, document the process of drawing a use case diagram

**Comment by MucahitErdoganUnlu** [comment]
@Meminseeker does this issue still need to be open?

**Comment by ozankrkya** [comment]
Zenith Project is completed last semester.
I am closing this issue since we have started to develop a new project from now on.
