### ISSUE TITLE
Draw class diagrams

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#133]
# 🧱 Description

For the second milestone, we need to have class diagrams of the application

To be reviewed by: @umitcan07 

## 📋 Acceptance Criteria

- [x] We have our Class diagram in the wiki

**Comment by umitcan07** [comment]
Reviewed and revised in a face-to-face meeting with @hks1444 and @tenacke.
Now it is in a good form. Thanks for the efforts
