### ISSUE TITLE
Create UI/UX designs

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#135]
# 🧱 Description

For the second milestone, we need to have UI/UX designs of the application for both mobile and desktop versions.

## 📋 Acceptance Criteria

- [x] We have responsive UX/UI designs for the Zenith App. (Either provide both versions or design mobile-first)

**Comment by Meminseeker** [comment]
We should have some assignees for this task now, obviously. Two or three people should be appropriate for this. I guess one of them is you @umitcan07 :) Who else gonna nail it??

**Comment by umitcan07** [comment]
Thanks for the issue
I would love to have someone else to be involved as well.

**Comment by umitcan07** [comment]
We are dealing with this with @hks1444

**Comment by umitcan07** [comment]
Here is the UX/UI Designs for the web and mobile guys. The designs are mobile-first.
Let me know if anything is missing any time.
Closing the issue, not to mean the comments and feedbacks are not welcome via Figma. Let's get the ux/ui discussion going on the Figma from now on
