### ISSUE TITLE
Update GitHub Roadmap

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#136]
# 🧱 Description

Update GitHub roadmap according to the second milestone of the project plan.

## 📋 Acceptance Criteria

- [ ] All the tasks of the second milestone are on the GitHub roadmap.
- [ ] All the tasks of the second milestone have a specific start and end date.

**Comment by Meminseeker** [comment]
We have reflected all the tasks of the second milestone to the GitHub [Roadmap](https://github.com/orgs/bounswe/projects/51/views/4). You can review it!

**Comment by MucahitErdoganUnlu** [comment]
Nice job!
