### ISSUE TITLE
Better categorize meetings

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#140]
# 🧱 Description

Right now we have merely enumerated meetings, they should be categorized into
- Weekly Sync, Requirements Meeting, Diagrams Meeting, Milestone Review etc.

## 📋 Acceptance Criteria

- [x] The meeting notes pages are renamed accordingly
- [x] The changes are reflected on the Wiki Sidebar

**Comment by yunuskaydin** [comment]
Changes on meeting notes pages are well renamed and could be seen on sidebar of the [wiki](https://github.com/bounswe/bounswe2024group11/wiki) page.
