### ISSUE TITLE
Update requirements page on Wiki

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#145]
# 🧱 Description

The requirements on Wiki needs to be updated.

## 📋 Acceptance Criteria

- [x] 1.1.1.3 has receiving email feature.
- [x] 1.1.1.4 has receiving email feature.
- [x] 1.1.2.2 has unlike feature.
- [x] 1.1.2.4 has unbookmark feature.
- [x] Search and browsing requirements are moved to user requirements.
- [x] 1.2.3.1 has unique email and username.

**Comment by tenacke** [comment]
I think this issue is can be closed. Your work seems completed and looks nice. Well done!
