### ISSUE TITLE
Draw Sequence Diagram for Search

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#148]
# 🧱 Description

Searching is consists of dew steps occuring in the backend. We will draw the sequence diagram displaying its flow. 

## 📋 Acceptance Criteria

- [x] General scheme of sequence is constructed.
- [x] A research about sequence diagrams is made.
- [ ] Sequence Diagram for Search is ready on wiki.

**Comment by ozankrkya** [comment]
I created the first version of sequence diagram for searching. 
- Few methods are necessary in class diagram indicating search operation in a list of objects(text fields of content list, high level search method initiated by user). 
- Some of the call arrows have ambiguous explanations. They have to be renewed when necessary methods added in class diagram. 

You can view the first version of the diagram below. 

![image](https://github.com/bounswe/bounswe2024group11/assets/101991332/c8463752-01f3-461e-aff3-f5a676eb964f)

**Comment by tenacke** [comment]
Your work looks nice! However we added new classes to the class diagram. From now on, we need to access posts through the 'Contents' class. This class works as a high level representation of the database that you drew in your sequence diagram. This 'Contents' class has find() method in order to represent the text search feature in contents. It is better to upgrade this sequence diagram by adding 'Contents' class.

**Comment by ozankrkya** [comment]
![search_sequence](https://github.com/bounswe/bounswe2024group11/assets/101991332/5437882d-e1e9-4c46-85de-e0cbc5f2bb17)

After feedbacks, this looks like its last version. I will upload it to wiki if it gets approved after revisions.

**Comment by tenacke** [comment]
Thank you for your work. However, I see a missing part. After selecting the correct Wikidata entity, our search engine should go to Wikidata and generate the info box for the selected entity. This info box has some new keywords that should be searched through the contents. There may be a loop for each keyword and after getting all the posts, ordering should be done by the weights that is come with the info box.

**Comment by Meminseeker** [comment]
As an alternative approach, we may retrieve the keywords for each entity at the beginning. By this, we get a bit larger response, of course, but we don't call Wikidata API twice. Which approach is more appropriate do you think?

**Comment by ozankrkya** [comment]
We have discussed the design of the implementation of the search mechanism. I am attaching the image of the decided sequence below.
![search_sequence](https://github.com/bounswe/bounswe2024group11/assets/101991332/efc258e5-0b42-4f2b-9c7c-9128b5b6da1f)
