### ISSUE TITLE
Documenting the Weekly Sync #11

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#150]
# 🧱 Description

Document the meeting notes for Weekly Sync 11.

## 📋 Acceptance Criteria

- [x] Weekly Sync 11 notes are well documented.

**Comment by meminciftci** [comment]
Weekly sync 11 has been added to repository: [here](https://github.com/bounswe/bounswe2024group11/wiki/Weekly-Sync-%2311)

**Comment by yunuskaydin** [comment]
Muhammet Emin Çiftçi has documented Weekly Sync in a correct, proper way.

**Comment by Meminseeker** [comment]
A photo of us from the meeting was missing...

**Comment by Meminseeker** [comment]
I uploaded a happy frame of us. Check it [here](https://github.com/bounswe/bounswe2024group11/wiki/Weekly-Sync-%2311) @meminciftci

**Comment by Meminseeker** [comment]
I'm closing this issue
