### ISSUE TITLE
Make a poll to find out team members' experiences and interests

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#154]
# 🧱 Description

In the project's implementation phase, there will be some sub-teams, such as backend and frontend.

Learning each team member's past experiences is necessary to form these sub-teams properly and wisely. Create a form to collect this information. It must cover various aspects, from the frontend to the backend, including DevOps.

Also, remember to include a question about the team members' preferences for this project. It is much better for everyone to work in their pleased positions as much as possible.

## 📋 Acceptance Criteria

- [x] We have a poll asking for past experiences of the team members in different aspects
- [x] Make team members fill out the form

**Comment by Meminseeker** [comment]
I've created the [form](https://forms.gle/8oeJ1dQ6iapBwmKS8)

**Comment by Meminseeker** [comment]
Eight out of 10 people filled out the form, and we also talked with the other two people in a meeting. It helps us to shape the sub-teams in the weekly meeting.

Can one of you guys confirm the situation and close this issue?

**Comment by umitcan07** [comment]
Insightful form, thanks. 🌟 
Closing the issue.
