### ISSUE TITLE
Form the sub-teams for the implementation phase

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#159]
# 🧱 Description

It is needed to divide our team into sub-teams of frontend and backend. The information represented in the form mentioned in #154 might be helpful.

## 📋 Acceptance Criteria

- [x] We have our team divided into sub-teams of frontend and backend

**Comment by Meminseeker** [comment]
In the weekly meeting, we divided our team into two subteams. 
The frontend team is responsible for both the web and mobile frontend.
The backend team is responsible for the backend and most DevOps tasks, such as hosting the database.

Frontend: @tenacke @hks1444 @meminciftci @ArdaVural @umitcan07 
Backend: @Meminseeker @MucahitErdoganUnlu @yunuskaydin @ceydanursen @ozankrkya

**Comment by umitcan07** [comment]
Teams have been formed, closing the issue.
Thanks everyone
