### ISSUE TITLE
Learn and research how to initialize the project

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#160]
# 🧱 Description

In the backend, it is chosen to use Django REST framework; in the web frontend, it is chosen to use React; in the mobile frontend, it is chosen to use React Native.

So, it is needed to determine how to structure the project as well as to learn how to initialize these sub-apps with these technologies.

## 📋 Acceptance Criteria

- [x] Determine the project structure
- [x] Learn how to initialize the backend app with Django REST Framework
- [x] Learn how to initialize the web frontend app with React
- [x] Learn how to initialize the mobile frontend app
- [x] Document the above steps in the wiki

**Comment by Meminseeker** [comment]
This is the initial version of the [documentation](https://github.com/bounswe/bounswe2024group11/wiki/How-to-initialize-a-backend-app-using-Django-REST-Framework). There are some missing points I mentioned at the end.

**Comment by ozankrkya** [comment]
Zenith Project is completed last semester.
I am closing this issue since we have started to develop a new project from now on.
