### ISSUE TITLE
Initialize the project

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#161]
# 🧱 Description

The project should be initialized and pushed back to GitHub, so that every developer can start to development. The artifacts of #160 might be helpful.

## 📋 Acceptance Criteria

- [x] Create an appropriate project structure
- [x] Initialize the backend app
- [x] Add gitignore files for each sub-apps
- [x] Add requirements.txt file for the backend app

**Comment by Meminseeker** [comment]
I guess you @umitcan07 @tenacke  guys initialize the web and mobile frontend app, respectively. Can you confirm please

**Comment by Meminseeker** [comment]
Then this issue can be closed now after a review.

Can one of you confirm the building of the project structure and the initialization of the backend app?
@ceydanursen @MucahitErdoganUnlu @yunuskaydin @ozankrkya

**Comment by MucahitErdoganUnlu** [comment]
We all have cloned the project repo to our locals. Closing it. Thank you!
