### ISSUE TITLE
Documenting the Weekly Sync #12

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#166]
# 🧱 Description

Document the meeting notes for Weekly Sync 12.

## 📋 Acceptance Criteria

- [ ]  Weekly Sync 12 notes are well documented.

**Comment by yunuskaydin** [comment]
Meeting notes of weekly sync 12 can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Weekly-Sync-%2312)

Our photo is missing...

**Comment by meminciftci** [comment]
There should not be a status column for the action items as it is decided [here](https://github.com/bounswe/bounswe2024group11/discussions/120)

**Comment by yunuskaydin** [comment]
I removed the status column as agreed. New note could be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Weekly-Sync-%2312)
@meminciftci

**Comment by meminciftci** [comment]
It looks clean and complete.

**Comment by Meminseeker** [comment]
And our photo is not missing now 🤩
