### ISSUE TITLE
 Bootstrap Frontend Application

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#167]
# 🧱 Bootstrap Frontend Application

We need to create an initial frontend document to start our development process.

## 📋 Acceptance Criteria

- [X] We have decided the technologies and libraries to use in frontend.
- [ ] We have an initialized our frontend application with some basic dependencies (tailwind and cva for styling, eslint and prettier for code styling etc.)

**Comment by umitcan07** [comment]
We have settled on the technologies we will use [here](https://github.com/bounswe/bounswe2024group11/discussions/179).
