### ISSUE TITLE
Documenting the Backend Meeting #1

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#175]
# 🧱 Description

Document the meeting notes for Backend Meeting 1.

## 📋 Acceptance Criteria

- [ ] Backend Meeting 1 notes are well documented.

**Comment by yunuskaydin** [comment]
Backend Meeting 1 notes could be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Backend-Meeting-%231).
@Meminseeker will add our photo.

**Comment by Meminseeker** [comment]
I've uploaded the photo

**Comment by Meminseeker** [comment]
I suggest specifying to implement the tutorial in addition to watching it, in the action items.

**Comment by yunuskaydin** [comment]
I also specified to implement the tutorial on action items [here](https://github.com/bounswe/bounswe2024group11/wiki/Backend-Meeting-%231)

**Comment by Meminseeker** [comment]
I guess this issue can be closed now
