### ISSUE TITLE
Design an open graph image for repo

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#18]
# 🧱 Description

An open graph image for the repository.

## 📋 Acceptance Criteria

- [x] The repo has an open graph image in the correct dimensions, with a sufficiently elegant design.

**Comment by umitcan07** [comment]
![Open Graph](https://github.com/bounswe/bounswe2024group11/assets/68506701/79e7010e-eb55-4203-8467-edfdb6fecd6c)

**Comment by MucahitErdoganUnlu** [comment]
Good job
