### ISSUE TITLE
Update RAM according to implementation phase

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#180]
# 🧱 Description

For the implementation phase, the team was divided into two main groups. Add this info to [Responsibility Assignment Matrix (RAM)](https://github.com/bounswe/bounswe2024group11/wiki/Responsibility-Assignment-Matrix) table

## 📋 Acceptance Criteria

- [x] We have people assigned to either frontend or backend in the RAM table

**Comment by Meminseeker** [comment]
I've updated the RAM. You can check and close it now

**Comment by tenacke** [comment]
Well done!
