### ISSUE TITLE
Document how to start development for the backend

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#181]
# 🧱 Description

When a new person want to start development for the backend part, he needs to do some setup in his local computer. Document these steps in the wiki.

## 📋 Acceptance Criteria

- [x] We have the specified document in the wiki

**Comment by Meminseeker** [comment]
I've documented the process for new developers to do in their local computers [here](https://github.com/bounswe/bounswe2024group11/wiki/How-to-Prepare-Your-Local-PC-for-the-Backend-Development).

I'm waiting to hear feedback from you

**Comment by Meminseeker** [comment]
#191 is also related to this issue

**Comment by Meminseeker** [comment]
Please review and close this issue

**Comment by tenacke** [comment]
It seems nice and descriptive, well done!
