### ISSUE TITLE
Create a page to document one or more favourite repos

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#19]
# 🧱 Description

Explore GitHub to discover some repositories that you like. Document at least one of them by providing a reference to the repo and describing what you liked about it.
This is a team assignment not individual.
## 📋 Acceptance Criteria

- [x] We have a wiki page that documents a repo.

**Comment by ozankrkya** [comment]
I created the wiki page about repository research task and made the first entry.
