### ISSUE TITLE
Review requirements

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#195]
# 🧱 Description

Teaching assistant provided feedback about our requirements according to the first customer milestone. The requirements need to be updated so that it complies with the feedback

**Comment by yunuskaydin** [comment]
New version is [here](https://github.com/bounswe/bounswe2024group11/wiki/Requirements). Your comments are needed. 

@MucahitErdoganUnlu

**Comment by MucahitErdoganUnlu** [comment]
a subtask: #321

**Comment by MucahitErdoganUnlu** [comment]
Removed comment section
