### ISSUE TITLE
Document the Research on Connecting Django to MySQL

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#203]
# 🧱 Description

Documenting the Research on Connecting Django to MySQL at the wiki page.

## 📋 Acceptance Criteria

- [ ] The Research on Connecting Django to MySQL is well documented.

**Comment by yunuskaydin** [comment]
First draft is [here](https://github.com/bounswe/bounswe2024group11/wiki/How-to-Connect-Django-to-MySQL). There may be additions on it.

**Comment by Meminseeker** [comment]
I think cloning the repository and creating a virtual environment should NOT be in this documentation. Maybe you can refer to the related wiki page at the beginning with a message like "You should prepare your local environment." 

Other than that, it is a clean and easy to implement documentation. After applying the steps, we can give another feedback about the commands, etc.

**Comment by yunuskaydin** [comment]
I removed cloning repo and creating a virtual environment. I added a small sentence that has links to them. You may see new documentation from [here](https://github.com/bounswe/bounswe2024group11/wiki/How-to-Connect-Django-to-MySQL).
