### ISSUE TITLE
Research and Find a Suitable UI Library

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#207]
# 🧱 Description

In order continue with our mobile development, a functional UI library is required.

## 📋 Acceptance Criteria

- [ ] A suitable UI library is  decided on for mobile development.

**Comment by tenacke** [comment]
We can use [RNUI lib](https://github.com/wix/react-native-ui-lib) because of its user friendly props and components.

**Comment by tenacke** [comment]
It is not a UI library but [React Navigation](https://reactnavigation.org/docs/) has nice and useful features in navigating.

**Comment by meminciftci** [comment]
We have decided on mostly using [React Native Paper](https://reactnativepaper.com/) and React Navigation.
