### ISSUE TITLE
Add Checks to API Endpoints for Improved Reliability and Security

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#208]
# 🧱 Description

We propose adding comprehensive checks to the existing API endpoints to enhance the reliability and security.

## 📋 Acceptance Criteria

- [x] Meaningful error messages and status codes are provided.
- [ ] Mechanism to authenticate requests is implemented.
- [x] Password field added successfully.

**Comment by Meminseeker** [comment]
I don't get what you mean by the second acceptance criteria. Can you explain it?

**Comment by ceydanursen** [comment]
Yes, you are right. In this step, we do not need to handle authentication.

**Comment by ceydanursen** [comment]
I have implemented checks for status codes and added password field to our CRUD endpoints. However, we decided to update our endpoints as token based endpoints.
