### ISSUE TITLE
Create Entity-Relationship (ER) and Relational Diagrams for Database Schema

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#209]
# 🧱 Description

Creating ER and relational diagram will help visualize the structure of our data model and plan the database schema more effectively.

## 📋 Acceptance Criteria

- [ ] ER diagram is created.
- [x] Relational diagram is created .

**Comment by MucahitErdoganUnlu** [comment]
Relational Diagram can be found [here](https://github.com/bounswe/bounswe2024group11/wiki/Relational-Diagram).
It contains tables for registered_user, blocked_list, muted_list, following_list, follower_list, post and profile

**Comment by ceydanursen** [comment]
After discussing the class diagram with Emre, we have decided to make some revisions. Once these changes are implemented, the relational diagram will be updated accordingly.

**Comment by Meminseeker** [comment]
If you're comfortable with this, it is totally okay to skip drawing the ER diagram.

**Comment by Meminseeker** [comment]
I have some feedback at the first glance. I'll write detailed feedback ASAP

**Comment by MucahitErdoganUnlu** [comment]
Feedback received from Muhammet Emin Arayıcı:
* password is duplicate in Registered_User
* phone, address, type is unnecesasry fields of registered user
* registered user is missing user id as its primary key
* all lists should use user id as foreign key
* no need for counters in Post. they should be computed on the fly
* email not needed in Profile

**Comment by MucahitErdoganUnlu** [comment]
Currently, all of the bullet points are done except for 
* comment, like, and bookmark should be a relation between Post and registered user

**Comment by MucahitErdoganUnlu** [comment]
Since Django handles Database management instead of us, we do not need conceptual diagrams desperately. closing it
