### ISSUE TITLE
Host a MySQL Database for the test environment on the cloud

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#216]
# 🧱 Description

MySQL is used as the project database. However, each developer use his local MySQL servers while developing, which has some inconveniences. It is needed to have a hosted database accessible by all the developers

## 📋 Acceptance Criteria

- [x] We have a hosted MySQL database instant

**Comment by Meminseeker** [comment]
I've created a MySQL database instant on [Digital Ocean](https://www.digitalocean.com/) platform. I tried to connect it remotely and succeeded. 

I'm sharing the secrets with the team members in a safe manner. 
@yunuskaydin You can review and close the issue

**Comment by yunuskaydin** [comment]
We had a small meeting with Muhammed Emin Arayıcı while he showed how to host the database. MySQL database is hosted.
