### ISSUE TITLE
Dockerize the backend app

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#218]
# 🧱 Description

The backend app, which is written in Django REST Framework, should be dockerized.

## 📋 Acceptance Criteria

- [x] The backend app dockerized
- [x] The docker image of the backend app is pushed to a container image registry platform

**Comment by ozankrkya** [comment]
We have final form of docker-compose file in main where we have separate containers for backend, web and db services. I am closing this issue.
