### ISSUE TITLE
Create a Sidebar for Wiki Page

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#22]
# 🧱 Description

Add & Customize a sidebar for wiki page that makes pages easily accessible and look organized. 

## 📋 Acceptance Criteria

- [ ] Wiki page has a customized sidebar.

**Comment by ozankrkya** [comment]
Created initial entries, not closing this issue since you can add other pages under it. 
Also we can list members under sidebar along with another page to display. Please leave your comments.

**Comment by umitcan07** [comment]
Thanks so much @ozankrkya I am taking this over from you. Will explore and see what we can do to enhance.

**Comment by umitcan07** [comment]
Beatufied the Sidebar, formatted accordingly. It works well enough for our purposes, as we add new sections and pages; we definitely can further enhance it. Closing the issue.
