### ISSUE TITLE
Write API tests for the User model

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#222]
# 🧱 Description

For the user model in the backend, it is needed to write unit tests.

## 📋 Acceptance Criteria

- [x] We have unit tests for the all endpoints of the User model

**Comment by MucahitErdoganUnlu** [comment]
We wrote tests for CRUD endpoints [here](https://github.com/bounswe/bounswe2024group11/pull/224). However, now that we do not use CRUD, they are obsolete. We will create register and login endpoints and write tests for them
