### ISSUE TITLE
Research how to store image fields and document it on wiki page

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#230]
# 🧱 Description

We have to store image fields in backend. Since we don't know how to do it, we must make a research and document a wiki page on it.

## 📋 Acceptance Criteria

- [x] Research on storing image fields is documented on wiki page.

**Comment by yunuskaydin** [comment]
Initial draft of storing images with Django framework and MySQL could be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/How-to-Store-Image-Fields).

**Comment by tenacke** [comment]
I saw that this issue is already done and remained open, I am closing it now.
