### ISSUE TITLE
Inherit from Django's User Model

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#246]
# 🧱 Description

Currently, our User model inherits from Django's generic models.Model class. In order to use Django's User class functionalities, update the code so that our User model inherits from Django's AbstractBaseUser or AbstractUser.

**Comment by yunuskaydin** [comment]
Code is updated in order to use Django's User class functionalities. It worked when i tried it on my local and PR is closed so I'm closing this issue. Good job! @MucahitErdoganUnlu
