### ISSUE TITLE
Implement Register and Login API Endpoints

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#247]
# 🧱 Description

We currently have CRUD API endpoints for the user model. However, we need register and login API endpoints for the user model because register and login requests must adhere to authentication. Therefore, implement register and login API endpoints for the User model.

**Comment by Meminseeker** [comment]
- Now, the User model extends the default user model of Django. Previously, we wrote a custom user model from scratch.
- Passwords are saved in hashed form in the database.
- Both endpoints return a session token as a response to successful calls. Previously, the login mechanism was based on 'Basic Auth'.
