### ISSUE TITLE
Write Tests For Register and Login API Endpoints

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#248]
# 🧱 Description

Register and login API endpoints should work properly. For example, a nonregistered username shall not be able to login. To save time, write unit tests to check their functionalities.

**Comment by Meminseeker** [comment]
The tests work properly, both for the `login` and `register` endpoints.

It is enough for now. Later, maybe we can add some test cases to check error codes as well.
