### ISSUE TITLE
Connect Backend to Hosted Database

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#261]
# 🧱 Description

Muhammed Emin Arayıcı hosted a MySQL database with this [issue](https://github.com/bounswe/bounswe2024group11/issues/216). We must connect this hosted database to our backend.

## 📋 Acceptance Criteria

- [ ] Hosted database is well connected to backend.

**Comment by yunuskaydin** [comment]
Hosted database is connected to our backend. This might seen in this [settings.py](https://github.com/bounswe/bounswe2024group11/blob/feature/db_connection/backend/config/settings.py) between lines of 81-90 which is in db_connection branch.

**Comment by ozankrkya** [comment]
It looks fine and working, thanks for your work.
