### ISSUE TITLE
Set up a Bruno API Client environment

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#266]
# 🧱 Description

We should have Bruno (Postman alternative) set up in the repository so that everyone can run and test Backend API endpoints without needing to configure anything

## 📋 Acceptance Criteria

- [x] We have our Bruno workspace in the repository.
- [x] There are test and production environments defined with our current endpoints.

**Comment by umitcan07** [comment]
Tested within multiple devices, including those of @yunuskaydin @meminciftci and mine.

**Comment by Meminseeker** [comment]
We have defined three distinct environment configurations in the [`bruno/` directory](https://github.com/bounswe/bounswe2024group11/tree/develop/bruno). The environments are `localhost`, `test-env`, and `prod`.

**Comment by Meminseeker** [comment]
This tool allows us to save and share our test configurations for the APIs we develop. With its easy-to-use interface, I love it too much. Thanks for your suggestion @umitcan07
