### ISSUE TITLE
Create personal efforts page

### ISSUE THREAD

**Issue by tenacke** [bounswe/bounswe2024group11#27]
# 🧱 Description

Create a personal efforts page in wiki

## 📋 Acceptance Criteria

A personal efforts page is created  

- [x] Arda Vural
- [x] Ceydanur ŞEN
- [x] Emre Kılıç
- [x] Hasan Kerem Şeker
- [x] Muhammed Emin Arayıcı
- [x] Muhammet Emin Çiftçi
- [x] Mücahit Erdoğan Ünlü
- [x] Ozan Oytun Karakaya
- [x] Ümit Can Evleksiz
- [x] Yunus Kağan Aydın

**Comment by umitcan07** [comment]
@tenacke @yunuskaydin Can you sort these out asap.
