### ISSUE TITLE
Create a documentation page on how to use Bruno client

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#270]
# 🧱 Description

A proper documentation page must be written on how to use Bruno client in order to observe backend operations.

## 📋 Acceptance Criteria

- [x] A proper documentation page is written on how to use Bruno client.

**Comment by umitcan07** [comment]
added within the PR #267 
Here is the Here is the [Wiki page](https://github.com/bounswe/bounswe2024group11/wiki/Using-Bruno-to-test-API) as well
