### ISSUE TITLE
Modify Response Codes

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#277]
# 🧱 Description

In Bruno, response codes are not well organized. It must lead to proper response codes such as 201 in signup ok, 200 in login ok and 400 in missing credientials, 401 in wrong credientials.

## 📋 Acceptance Criteria

- [x] Response codes are modified in a correct way.

**Comment by umitcan07** [comment]
PR didnt seem to work, closing manually.
