### ISSUE TITLE
Bootstrap a meeting notes template

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#28]
# 🧱 Description

We should create a note template to fill in for each meeting. It should include

- The structure we used for [Home page](https://github.com/bounswe/bounswe2024group11/wiki)
- The general info: Date, Time, Duration, Participants table
- Discussion Points section. (The flow of the meeting in general)
- Actions section with a table: what to do, who is responsible, the relevant issue(s)
- An optional additional notes section

## 📋 Acceptance Criteria

- [x] We have a reusable, well-organized MD template with the aforementioned specifications.

**Comment by meminciftci** [comment]
I have written a meeting notes template: [Meeting Notes Template](https://github.com/bounswe/bounswe2024group11/wiki/Meeting-Notes-Template)

**Comment by umitcan07** [comment]
We need to further get deeper into action items and agenda. Check discord out for more details.

**Comment by meminciftci** [comment]
@umitcan07 I have updated the points you mentioned: [Meeting Notes Template](https://github.com/bounswe/bounswe2024group11/wiki/Meeting-Notes-Template)

**Comment by umitcan07** [comment]
@meminciftci lgtm
