### ISSUE TITLE
Dockerize the database of the backend app

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#285]
# 🧱 Description

As database, we use a fully managed MySQL database on the cloud. However, for the production environment, we need to have a dockerized database.

## 📋 Acceptance Criteria

- [x] We have a MySQL server running in a Docker container
- [x] The dockerized backend app can work with this dockerized database.
- [x] This multi-container architecture works in a deployed environment

**Comment by Meminseeker** [comment]
Our database is running in a Docker container. You can review the [docker-compose file](https://github.com/bounswe/bounswe2024group11/blob/main/docker-compose.yml).

This container is currently running at our production server, whose IP address is `159.65.125.158`.
