### ISSUE TITLE
Send request to backend from Login and Register routes

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#289]
# 🧱 Description

Now that we have our login and register routes with good UX/UI, we should send a POST request to the backend endpoints within these routes.

## 📋 Acceptance Criteria

- [x] Login and Register routes have actions to send request to backend and they act according to the response.

**Comment by tenacke** [comment]
I see that #298 solved this issue, so I am closing it now. Nice work!
