### ISSUE TITLE
Write down the first meeting notes to the template

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#29]
# 🧱 Description

Fill in the meeting notes template by the [Google Drive Document](https://docs.google.com/document/d/1W4iK7rXuw1T8TlPYTqooK_2ua9cKA7ZYRhsNcQY_oD8/edit#heading=h.2f6rif2oj6r9)

Blocked by #28 

## 📋 Acceptance Criteria

- [x] #28 is closed
- [x] We have the first meeting note in the form of the template described in #28

**Comment by meminciftci** [comment]
I have bootstrapped [the meeting notes template](https://github.com/bounswe/bounswe2024group11/wiki/Meeting-Notes-Template) and documented the [meeting #1 notes](https://github.com/bounswe/bounswe2024group11/wiki/Meeting-%231) in the form of the template.

**Comment by umitcan07** [comment]
@meminciftci Looking very good. Good job! Just a reminder to organize action items by the units of work rather than by people. So if a person is supposed to do 3 jobs, we should have 3 table rows, not 1.

Apart from that, I really liked the formatting. Thank you
