### ISSUE TITLE
Research and Document How to Write Swagger UI for Django REST API

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#291]
# 🧱 Description

Document a step-by-step guide on how to write custom Swagger UI components on Django Rest framework.

**Comment by MucahitErdoganUnlu** [comment]
The [guide](https://github.com/bounswe/bounswe2024group11/wiki/Tutorial-on-How-to-Write-and-Use-Swagger-API) on how to use and implement Swagger UI is documented.

**Comment by yunuskaydin** [comment]
I read the document line by line. It is neatly written. Congrats @MucahitErdoganUnlu!
