### ISSUE TITLE
Create an automated CI/CD pipeline for the production environment

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#305]
# 🧱 Description

There are lots of pushes to the `main` branch and it is needed to deploy them in a production environment. It is very hard to do this manually after every push. Create a CI/CD pipeline which automates the deployment of the `main` branch to the production environment.

## 📋 Acceptance Criteria

- [x] Every change on the `main` branch triggers an automated CI/CD pipeline
- [x] The main branch is deployed to a production environment

**Comment by Meminseeker** [comment]
- The secrets needed are defined in the repo settings (E.g., SSH_HOST, etc.)
- We have an automated CI/CD pipeline triggering by any change in the `main` branch. You can review the defined [workflow](https://github.com/bounswe/bounswe2024group11/blob/develop/.github/workflows/main.yml).
- We have our [production environment](http://159.65.125.158:5173/login) where our CI/CD pipeline deploys the `main` branch.


Later, maybe we can automate our tests, etc., in this pipeline as well. For now, it is very sufficient.

**Comment by tenacke** [comment]
I see that the automated CI/CD pipeline is triggered well, and we have our production environment where the main branch is deployed. I think we can close this issue. Thanks for your work!
