### ISSUE TITLE
Add a README file for the mobile app

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#307]
# 🧱 Description

Our mobile app needs to have a README file for others to run it as well as to start development.

## 📋 Acceptance Criteria

- [x] We have a README file explaining how to build/start mobile app

**Comment by Meminseeker** [comment]
With the help of @tenacke, I wrote a [README file](https://github.com/bounswe/bounswe2024group11/blob/develop-mobile/mobile/README.md) containing steps for how to start our mobile app.

**Comment by yunuskaydin** [comment]
The alt text at the end of the [README file](https://github.com/bounswe/bounswe2024group11/blob/develop-mobile/mobile/README.md) returns page with 404 error as the image doesn't exist. We should take a look on that.

**Comment by tenacke** [comment]
The readme is on the repo. We can close this for now.
