### ISSUE TITLE
Add functionalities to the buttons on signup page for mobile

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#308]
# 🧱 Description

From signup page, a user shall be able to sign up. Communication with database should be provided.

## 📋 Acceptance Criteria

- [x] Register button has a functionality of signing up the new users.
- [x] After pressing register button, it should either be successful or give corresponding error with respect to the provided fields.

**Comment by ArdaVural** [comment]
Register button is implemented without any problem.
