### ISSUE TITLE
Fix the Cors problem in frontend/web requests

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#323]
# 🧱 Description

We used no-cors header with requests before, however, it doesn't allow to see the response from backend since it sends opaque responses. A configuration in backend should include web server to allowed origins in backend/config/settings.py.
## 📋 Acceptance Criteria

- [x] Cors error is resolved.

**Comment by umitcan07** [comment]
We now respond with a header!

**Comment by ozankrkya** [comment]
We have resolved this issue by branching a cors branch, resolved it and merged to the develop branch. I am closing this issue.
