### ISSUE TITLE
Research and Document Good Backend Developer Practices

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#332]
# 🧱 Description

Mücahit previously returned JSON Response message bodies randomly. For example, in the same Django REST view, he returned `{'error': 'Failed to retrieve data from Wikidata.'}` at some part and `{"res":"Please provide a valid keyword."}` in another. However, `error` or `res` are important for the frontend to develop. Therefore, a consistent payload field names should be followed. These kind of good practices should be researched and documented.

**Comment by MucahitErdoganUnlu** [comment]
* Suzan Hoca mentioned `Test-driven development`

**Comment by MucahitErdoganUnlu** [comment]
refer to [pip freeze > requirements.txt considered harmful](https://medium.com/@tomagee/pip-freeze-requirements-txt-considered-harmful-f0bce66cf895) @Meminseeker

**Comment by Meminseeker** [comment]
From now on, we'll update our `requirements.txt` file by hand. You can announce this in the discussions section @MucahitErdoganUnlu 

Thanks for the document, it explains it thoroughly

**Comment by Meminseeker** [comment]
But I guess your issue description needs to be updated. Let's take a look at together :)

**Comment by MucahitErdoganUnlu** [comment]
python manage.py migrate profiles zero

**Comment by MucahitErdoganUnlu** [comment]
https://drf-yasg.readthedocs.io/en/stable/custom_spec.html?highlight=swagger_auto_schema#:~:text=for%20ViewSet%2C%20GenericViewSet%2C%20ModelViewSet%2C

**Comment by ozankrkya** [comment]
Zenith Project is completed last semester.
I am closing this issue since we have started to develop a new project from now on.
