### ISSUE TITLE
Use React Query

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#335]
# 🧱 Description

We are currently using fetch but it is not scalable and maintainable. So we need to use a thorough query library like react query.

## 📋 Acceptance Criteria

- [ ] We use react query instead of manual fetch
- [ ] React Query research is documented on the wiki page.

**Comment by umitcan07** [comment]
We might actually use [SWR](https://swr.vercel.app/).
Let's think about the adv/disadv of these two and then decide what to use
