### ISSUE TITLE
Replace Dialog with Toast Notification component

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#339]
# 🧱 Description

When an error occurs in the application (Auth error on login), we inform users via a Dialog component. It's not a best practice, since it does not include the necessary attributes to cement itself as a Error/Info/Warning type of component. It's especially important for screen readers.

## 📋 Acceptance Criteria

- [ ] We use the `Notification` component on login and register, instead of the `Dialog`

**Comment by hks1444** [comment]
I accidentally pushed my changes directly to the develop-web branch. You can check [my commit](https://github.com/bounswe/bounswe2024group11/commit/a6e66b79ffd9fb7807761338285bac6d1d6bb97b).
