### ISSUE TITLE
Update project structure in readme

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#342]
# 🧱 Description

## 📋 Acceptance Criteria

- [ ] The project structure section on the root readme file includes how the source code is organized as "kind-of-and-asci" art

**Comment by hks1444** [comment]
What do you mean my "kind-of-and-asci"?

**Comment by umitcan07** [comment]
@hks1444 

```bash
├── src
│   ├── connectors
│   │   ├── actions
│   │   ├── api
│   │   └── hooks
│   ├── helpers
│   ├── models
│   │   ├── interfaces
│   │   └── types
│   ├── pages
│   ├── state
│   └── ui
│       ├── atoms
│       ├── components
│       ├── icons
└── ...
```

**Comment by hks1444** [comment]
Zenith Project is completed last semester.
I am closing this issue since we have started to develop a new project from now on.
