### ISSUE TITLE
Research how to store image fields for posts

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#344]
# 🧱 Description

Our application will allow users to upload photos as they share them with their posts. Since images are different from text-based entities, research is needed to find a proper way to store and use images in the application.

## 📋 Acceptance Criteria

- [x] We have a document explaining the options about how to store image fields
- [x] We chose an approach to follow

**Comment by yunuskaydin** [comment]
We selected the way of getting images from URL's. So no document is needed.
