### ISSUE TITLE
Build endpoints for `Post`

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#345]
# 🧱 Description

Building `Post` related endpoints is necessary as our application needs to have posts and some other post-related functionalities. Focus on the CRUD endpoints of the `Post` model right now.

## 📋 Acceptance Criteria

- [ ] Write Swagger UI specifications of the `Post` model
- [ ] Write unit tests for the endpoints of the `Post` model
- [ ] Write endpoints of the `Post` model

**Comment by hks1444** [comment]
Zenith Project is completed last semester.
I am closing this issue since we have started to develop a new project from now on.
