### ISSUE TITLE
Create an endpoint for the  profile 

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#388]
# 🧱 Description

The objective is to establish a functional endpoint that facilitates the retrieval and manipulation of user profiles within the system.

## 📋 Acceptance Criteria

- [ ] Profile includes  the following fields: biography, profile picture and username.

**Comment by ozankrkya** [comment]
I will review the code and merge this branch after the review to develop-backend2.

**Comment by ceydanursen** [comment]
Implemented endpoint includes the following fields: biography, profile picture and username correctly.
