### ISSUE TITLE
Move links to the relevant places & remove hardcoded URL's

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#39]
# 🧱 Description

Currently, some of the Wiki pages of ours has hardcoded URLs as links to various sites. For better readability and maintainability, we need to use text-as-links

Example:

❌ https://www.google.com
✅ [Google](https://www.google.com)

We can use this compact version in the following pages:

- [Resources](https://github.com/bounswe/bounswe2024group11/wiki/Resources) -> Use titles as links, rather than having the link below
- [Git Tutorial](https://github.com/bounswe/bounswe2024group11/wiki/Git-Tutorial) 
- [Repository Research](https://github.com/bounswe/bounswe2024group11/wiki/Repository-Research) -> Use titles as links. rather than having "here" button.

Tip: If you highlight a text and paste a link whilst it is selected, Github will automagically do the linking for you!

## 📋 Acceptance Criteria

- [ ] The Aforementioned pages have links in compact view.

**Comment by ArdaVural** [comment]
removed hardcoded links and fixed headers emojis

**Comment by umitcan07** [comment]
@ArdaVural Looking clean! Thanks.
