### ISSUE TITLE
Merge Backend Version 2 to Current Development Server

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#414]
# 🧱 Description

New developments on backend side are made under backend2 folder, with a new version. That should be deployed on development server and merged as new backend.
## 📋 Acceptance Criteria

- [ ] New version is running on development server.

**Comment by tenacke** [comment]
Please remember not to delete the old branch.

**Comment by ozankrkya** [comment]
Conducted this operation successfully, good job guys !!!
