### ISSUE TITLE
Implement a parallel backend

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#456]
# 🧱 Description

There are some issues on the backend app that are hard to debug. Trying to implement a parallel backend app from scratch while the team should continue to work on the old app is needed. Please be aware that don't remove the old backend in this process. Only if comprehensive tests and assessments of the new backend app is confirmed, then we can drop the old one and deploy the new one.

We need to see if building a backend app from scratch works AS SOON AS POSSIBLE since we have so little time till the milestone!

## 📋 Acceptance Criteria

- [x] We have a new backend app satisfying all working functionalities of the old backend
- [x] We have a new backend satisfying, at least, some of the non-working functionalities of the old backend

**Comment by hks1444** [comment]
Zenith Project is completed last semester.
I am closing this issue since we have started to develop a new project from now on.
