### ISSUE TITLE
Implement a JWT based authentication

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#458]
# 🧱 Description

We use a token-based authentication. However, the usage of tokens for API calls differs between web and mobile parts. If we use JSON Web Token (JWT) based authentication, we can unify the logic here.

## 📋 Acceptance Criteria

- [x] We have a JWT based authentication

**Comment by ozankrkya** [comment]
Zenith Project is completed last semester.
I am closing this issue since we have started to develop a new project from now on.

**Comment by hks1444** [comment]
Zenith Project is completed last semester.
I am closing this issue since we have started to develop a new project from now on.
