### ISSUE TITLE
Learn the fundamentals of Monorepo concept

### ISSUE THREAD

**Issue by tenacke** [bounswe/bounswe2024group11#46]
# 🧱 Description

Monorepo might be useful for our project in the future, so it is better to explore what it is and what is possible with it.

## 📋 Acceptance Criteria

- [ ] Ability to express what Monorepo is and what is possible with Monorepo

**Comment by umitcan07** [comment]
https://turbo.build/ can be the way to go if we were to settle on a fully JS/TS stack.

**Comment by umitcan07** [comment]
@tenacke If you have done enough to grasp only fundamentals, I think we should close this issue
