### ISSUE TITLE
Organize Repository by Moving it under /archive

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#460]
# 🧱 Description

Our old repository from Cmpe352 must be moved under /archive in order to have a new proper repository for our next project.

## 📋 Acceptance Criteria

- [x] Old repository is moved under /archive.

**Comment by ozankrkya** [comment]
Zenith Project is completed last semester.
I am closing this issue since we have started to develop a new project from now on.
