### ISSUE TITLE
Remove old unnecessary artifacts

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#461]
# 🧱 Description

The repository contains old unnecessary artifacts such as unused branches and issues.

## 📋 Acceptance Criteria

- [x] Delete unused branches
- [x] Close old issues

**Comment by hks1444** [comment]
Closed all old issues

**Comment by Meminseeker** [comment]
I deleted all unnecessary branches, which are all the branches except the main branch.

You can check them in the [branches](https://github.com/bounswe/bounswe2024group11/branches/all) page.
