### ISSUE TITLE
Organize New Meeting Schedule

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#462]
# 🧱 Description

We need a new meeting hour for weekly updates for CMPE451 semester. 
A new meeting schedule should be decided on with a poll.
## 📋 Acceptance Criteria

- [ ] Meeting time is decided for the group.

**Comment by ceydanursen** [comment]
The time for the weekly meeting is decided successfully.  You can see the determined time [here](https://github.com/bounswe/bounswe2024group11/wiki/Communication-Plan).
