### ISSUE TITLE
Document the Lab Meeting #1

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#463]
# 🧱 Description

Document the meeting notes for Lab Meeting 1.

## 📋 Acceptance Criteria

- [ ] Lab Meeting 1 notes are well documented.

**Comment by yunuskaydin** [comment]
Lab Meeting 1 notes can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Lab-Meeting-%231).

**Comment by meminciftci** [comment]
It has been reviewed. It seems all right.
