### ISSUE TITLE
Create Lab Report Template

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#469]
# 🧱 Description

We should create a lab report template in order to use it in upcoming weeks.

## 📋 Acceptance Criteria

- [ ] Lab Report Template is written.

**Comment by yunuskaydin** [comment]
Lab Report Template can be see [here](https://github.com/bounswe/bounswe2024group11/wiki/Lab-Report-Template).

**Comment by Meminseeker** [comment]
Lab report template should be updated. We add issue links to the objectives.

**Comment by yunuskaydin** [comment]
I added Issues column as it can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Lab-Report-Template).

**Comment by Meminseeker** [comment]
That's good. I'm closing the issue. But please note that you should check the marks in the issue description when you do them.
