### ISSUE TITLE
Create Requirements

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#471]
# 🧱 Description
The goal is to develop a set of requirements to guide our project’s next steps. These requirements will help clarify user needs and system constraints.

## 📋 Acceptance Criteria

- [x] A set of clear and concise requirements is defined based on the elicitation process.

**Comment by Meminseeker** [comment]
1. Requirements are [here](https://github.com/bounswe/bounswe2024group11/wiki/Requirements). It should be updated after asking elicitation questions.
2. Elicitation questions for the requirements are [here](https://github.com/bounswe/bounswe2024group11/wiki/Elicitation-Questions).

**Comment by ozankrkya** [comment]
Issue about Elicitation Questions are separated, can be viewed [here](https://github.com/bounswe/bounswe2024group11/issues/479).

**Comment by Meminseeker** [comment]
I have updated the [requirements](https://github.com/bounswe/bounswe2024group11/wiki/Requirements) page to match the elicitation questions. Thanks for your collaboration @MucahitErdoganUnlu

**Comment by Meminseeker** [comment]
The titles and descriptions of this issue and #479 should be rearranged since they are now separated into two issues.

**Comment by Meminseeker** [comment]
I have updated the issue title and description to clearly identify this issue and #479

**Comment by Meminseeker** [comment]
Now, this issue can be closed safely.
