### ISSUE TITLE
Research Lexvo

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#473]
# 🧱 Description

The purpose of this task is to research Lexvo, a resource that provides data about languages, words, and other linguistic entities. The findings will help determine how Lexvo can be integrated or utilized within our project. The research should include an overview of Lexvo's API, data formats, and potential use cases relevant to our needs.

## 📋 Acceptance Criteria

- [ ] Details on how Lexvo's API works, including authentication, data retrieval, and supported formats.
- [ ] Identification of potential use cases for Lexvo within the project.

**Comment by MucahitErdoganUnlu** [comment]
I have found two alternatives for Linked Data translation EN-TR: [Lexvo](http://www.lexvo.org/) and [BabelNet](https://babelnet.org/). Lexvo's database is very limited and its usage is not handy. On the other hand, BabelNet has a vast, useful linked database. Therefore, I recommend using BabelNet as our Linked Data structure.

I will further research usage of API of BabelNet if we agree on this.

**Comment by Meminseeker** [comment]
We decided to use BabelNet instead of Lexvo after discussing it within the team and asking the TAs.

After writing a short doc on how to use BabelNet API, this issue is okay to close, in my opinion.

**Comment by Meminseeker** [comment]
Also, we've agreed on these use cases for BabelNet:

1- While creating type-1 and type-2 quizzes (matching an English word its Turkish counterpart and matching a Turkish word with its English counterpart, respectively), the correct answer should come from BabelNet API. And the user should choose the correct translation from the retrieved options.
2- While creating type-3 quizzes (matching an English word with its sense), the correct answer should come from the BabelNet API. In addition, the senses in the wrong options should also come from the BabelNet API. For all options, the user should choose the correct senses from the retrieved options.
3- While searching quizzes, other semantically related words of a searched keyword should be retrieved from BabelNet. All of those keywords should be searched within the quizzes based on their tags.
4- While searching forum questions, other semantically related words of a searched keyword should be retrieved from BabelNet. All of those keywords should be searched within the forum questions based on their hashtags.
