### ISSUE TITLE
Document the Lab Meeting #2

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#477]
# 🧱 Description

The meeting notes for Lab Meeting 2 should be documented.

## 📋 Acceptance Criteria

- [x] Document the Lab Meeting 2.

**Comment by meminciftci** [comment]
Initial draft can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Lab-Meeting-%232)

**Comment by ArdaVural** [comment]
It looks completed. Good job.
