### ISSUE TITLE
Modify Elicitation Questions Page

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#479]
# 🧱 Description

During the elicitation phase of SRS, we have prepared questions to be asked to the customer. 

Answers and additional notes about elicitation questions are gathered during [Lab Meeting #2](https://github.com/bounswe/bounswe2024group11/wiki/Lab-Meeting-%232). 
[Requirement Elicitation](https://github.com/bounswe/bounswe2024group11/wiki/Elicitation-Questions) page on wiki should be updated accordingly.

## 📋 Acceptance Criteria

- [x] Requirement Elicitation page is now updated with the answers to questions.

**Comment by hks1444** [comment]
Good job. Elicitation questions page contains the necessary answers. I am closing this issue.

**Comment by Meminseeker** [comment]
I have updated the issue title and description to thoroughly identify this issue and #471
