### ISSUE TITLE
Create Use Case Diagrams

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#485]
# 🧱 Description
We need to create use case diagrams to represent the interactions between actors and the system, as well as the functionality provided by the system. These diagrams will help visualize the system's behavior, clarify requirements, and guide further development.

## 📋 Acceptance Criteria

- [x] Create use case diagrams showing actors, use cases, and relationships.
- [x] Add the diagrams to [wiki page](https://github.com/bounswe/bounswe2024group11/wiki/UML-Use-Case-Diagram)

**Comment by ozankrkya** [comment]
First version of the UML Use Case Diagram is ready on the wiki homepage for reviews.

**Comment by Meminseeker** [comment]
The link in the issue description is broken @ozankrkya

**Comment by ozankrkya** [comment]
I am closing this issue since we all decided on the final form of the UML Use Case diagram. 

It can be viewed on [wiki](https://github.com/bounswe/bounswe2024group11/wiki/UML-Use-Case-Diagram).
