### ISSUE TITLE
 Document Frontend Meeting #1

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#486]
# 🧱 Description

Meeting notes for the Frontend Meeting 1 should be documented.

## 📋 Acceptance Criteria

- [x] Document Frontend Meeting 1 meeting notes.

**Comment by yunuskaydin** [comment]
Initial draft can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Frontend-Meeting-%231-(CMPE451)).

**Comment by Meminseeker** [comment]
I have assigned myself to one of the TBD tasks. 

Now, it looks clean. I'm closing it.
