### ISSUE TITLE
Create Gannt and Network Charts for Project Planning 

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#487]
# 🧱 Description

Gannt Chart and Network Chart with their descriptions should be added to [project planning Wiki page](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan).

## 📋 Acceptance Criteria

- [x] Add necessary charts to project plan.

**Comment by meminciftci** [comment]
Charts can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan).

**Comment by Meminseeker** [comment]
The charts seem good as they reflect the current project plan.
