### ISSUE TITLE
Create User Scenario 2 - Search for a Quiz & Create a Quiz

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#489]
# 🧱 Description

A scenario for quiz search and quiz creation is needed for further stages like UI/UX design and implementation. The scenario has to include persona, goals, pre-conditions, and acceptance criteria.  

## 📋 Acceptance Criteria

- [x] Create a page for quiz search and quiz creation scenario
- [x] Create persona for scenario
- [x] Create goals for scenario
- [x] Create acceptance criteria for scenario
- [x] Create Mockups

**Comment by hks1444** [comment]
Created the scenario. You can see [here](https://github.com/bounswe/bounswe2024group11/wiki/User-Scenario-2).

**Comment by hks1444** [comment]
Added mockups to the scenario

**Comment by hks1444** [comment]
@ozankrkya The scenario is ready for review

**Comment by ozankrkya** [comment]
Reviewed the scenario with its goals, requirement coverage and mock-up screens. Good job guys.
