### ISSUE TITLE
Create User Scenario 4 - Search Forum & Bookmark & Upvote & Answer

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#491]
# 🧱 Description

User scenarios for forum usage inside the application should be created. Scenarios including all kinds of forum question features should be prepared with their stories.

## 📋 Acceptance Criteria

- [x] User Scenarios about forum usage inside the application is ready on wiki with the name of Scenario 4.
- [x] There are mockup screens for the steps in the scenario.

**Comment by ozankrkya** [comment]
Scenario 4 page is ready on wiki @ceydanursen along with its mock-up.

**Comment by ceydanursen** [comment]
Scenario 4 covers requirements stated and the mockups reflect the scenario successfully. Also story & persona is choosen nicely. Scenario 4 can be seen in [here](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-4)
