### ISSUE TITLE
Create User Scenario 1 - Explore and Register 

### ISSUE THREAD

**Issue by ArdaVural** [bounswe/bounswe2024group11#492]
# 🧱 Description
Create the user scenario for exploring and registering which is covering regarding requirements.

## 📋 Acceptance Criteria

- [x] There is a user scenario about exploring and registering.
- [x] There are mockup screens for the steps in the scenario.

**Comment by umitcan07** [comment]
[There you go](https://github.com/bounswe/bounswe2024group11/wiki/User-Scenario-1)

Can you review

**Comment by ArdaVural** [comment]
> [There you go](https://github.com/bounswe/bounswe2024group11/wiki/User-Scenario-1)
> 
> Can you review

Step titles should be imperative. We shoud check it again.

**Comment by ArdaVural** [comment]
Step titles are updated. 
Please review @meminciftci @umitcan07

**Comment by umitcan07** [comment]
I have added the mockups

**Comment by meminciftci** [comment]
[Scenario 1](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-1) looks clean and complete. Good job, closing the issue..
