### ISSUE TITLE
Create User Scenario 5 - View User Badge

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#494]
# 🧱 Description

Users are able to win user badges according to their follower counts, quiz scores, etc. A scenario including following of an user and viewing its follower count, user badge and new badge after one more follower count.

## 📋 Acceptance Criteria

- [x] Scenario including user follow interaction and badge interaction is written and ready on the wiki page under the name of Scenario 5.

**Comment by ozankrkya** [comment]
Scenario 5 page is ready on wiki with its mock-up.

**Comment by hks1444** [comment]
It looks good. I did not see any mistake. Keep up the good work.
