### ISSUE TITLE
Bootstrap Web Client Application

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#496]
# 🧱 Description

We should get the frontend app up with libraries and essentials such as framework, theming library, routing library.

## 📋 Acceptance Criteria

- [x] The main libraries to use are decided and installed.
- [x] The client app is ready to implement register / login pages.

**Comment by hks1444** [comment]
I merged the pr. Login and register are ready for implementation. The libraries are present.
