### ISSUE TITLE
Decide the Libraries to Use in the Client App

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#499]
# 🧱 Description

We should settle on the libraries for:

- Styling
- Routing
- Mock Server
- State Management

## 📋 Acceptance Criteria

- [x] #505
- [x] The project can be in a state that bootstrapping it is possible.

**Comment by umitcan07** [comment]
### Libraries
#### Styling
- TailwindCSS
- class-variance-authority (cva)
#### Routing
- React Router
#### Runtime 
- Node
#### Package Manager
- pnpm
#### Development Server & Tooling
- Vite
####  Linter
- ESLint
> Biome had caused some problems last semester
#### Formatter
- Prettier
> Biome had caused some problems last semester
#### Data Fetching
- SWR

**Comment by umitcan07** [comment]
Ready!

**Comment by Meminseeker** [comment]
What was the problem with `Biome`? @umitcan07 

Also, what are the pros and cons of choosing `pnpm` over `npm`?

**Comment by umitcan07** [comment]
@Meminseeker pnpm is way faster, we always found ourselves install libraries again. (especially docker compose up => pnpm build faster than npm build)

biome is way too new, it is a great formatter + linter but some of the stuff we need is missing. and i found it hard to find what i need from their docs.)

**Comment by hks1444** [comment]
I supported using npm because we had to switch back to npm in the previous semester, but now it works fine and is faster. Well done.
