### ISSUE TITLE
Determine the criteria of domain evaluation

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#50]
# 🧱 Description

In order for our team to choose a domain for the project, criteria of domain evaluation need to be clearly explained. 

## 📋 Acceptance Criteria

- [x] Criteria of domain evaluation are determined and clearly explained.

**Comment by MucahitErdoganUnlu** [comment]
https://github.com/bounswe/bounswe2024group11/wiki/Criteria-of-Domain-Evaluation#3-abundance-of-information
