### ISSUE TITLE
Create User Scenario 3 - Take & Review a Quiz

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#501]
# 🧱 Description

Create the user scenario for taking a quiz and reviewing it.

## 📋 Acceptance Criteria

- [x] There is a user scenario about taking and reviewing a quiz.
- [x] There are mockup screens for the steps in the scenario.

**Comment by Meminseeker** [comment]
Scenario 3 is [here](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-3). Thanks for your collaboration @MucahitErdoganUnlu 

You can review it @hks1444

**Comment by hks1444** [comment]
Sorry for the late review. Your scenario looks nice and I didn't see any error. Keep up the good work.
