### ISSUE TITLE
Document the Lab Meeting #3

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#502]
# 🧱 Description

The meeting notes for Lab Meeting 3 should be documented.

## 📋 Acceptance Criteria

- [x] Document the Lab Meeting 3

**Comment by meminciftci** [comment]
Document can be reached [here](https://github.com/bounswe/bounswe2024group11/wiki/Lab-Meeting-%233)

**Comment by umitcan07** [comment]
looking good

**Comment by yunuskaydin** [comment]
Document looks clean and complete.
