### ISSUE TITLE
Document Milestone Scopes

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#507]
# 🧱 Description

There are both dev milestones and customer milestones in the [project plan](https://github.com/bounswe/bounswe2024group11/blob/main/Project_Plan.pod). Document the scopes, explanations and deliverables of these milestones in the [wiki](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan).
## 📋 Acceptance Criteria

- [x] We have project milestones explained in the wiki.

**Comment by Meminseeker** [comment]
Scopes, explanations, and deliverables of the milestones are explained in the [wiki](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan).

**Comment by meminciftci** [comment]
Documentation looks clean and descriptive. Closing the issue..
