### ISSUE TITLE
Add Fields and Methods for Router (Class Diagram)

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#514]
# 🧱 Description
The router class has missing routes. These fields should be added for further understanding of this class.

## 📋 Acceptance Criteria

- [x] All routes are added to class.

**Comment by meminciftci** [comment]
I have added all the router methods, possibly including redundant ones. It needs to be reviewed. See [here](https://github.com/bounswe/bounswe2024group11/wiki/Class-Diagrams)

**Comment by meminciftci** [comment]
This issue was already completed. I am closing it.
