### ISSUE TITLE
Implement Login and Register Endpoints

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#516]
# 🧱 Description
We need to implement two key endpoints using simple-jwt for user authentication and registration in our Django REST API:

Token Obtain Pair Endpoint: This endpoint will allow users to obtain a JWT access and refresh token using their username and password.
Registration Endpoint: This endpoint will enable new users to register by providing their username and password.

## 📋 Acceptance Criteria

- [x] The Token Obtain Pair and Registration endpoints are implemented and accessible.
- [x] The Token Obtain Pair endpoint returns valid JWT tokens upon successful authentication.
- [x] The Registration endpoint successfully creates new users and handles validation errors appropriately.
- [x] Unit tests cover various scenarios for both endpoints.
- [x] Swagger documentation is generated.

**Comment by ArdaVural** [comment]
I tried and reviewed the PR in my local.  Added some necessary changes that @meminciftci requested.  Last version is merged.
