### ISSUE TITLE
Create Sequence Diagrams 

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#518]
# 🧱 Description
We need to create sequence diagrams to visualize the key interactions within the system for the app's use case workflows (#485). These diagrams will help communicate the interactions between different components from class diagrams (#484), making it easier to understand the logic and identify potential improvements or bottlenecks.
## 📋 Acceptance Criteria

- [x] All diagrams clearly depict each step with labeled lifelines and interactions.
- [x] Diagrams are consistent with the app's logic and workflows.
- [x] Diagrams use standard UML notation (arrows, lifelines, activation bars, etc.).
- [x] The diagrams are added to the [wikipage](https://github.com/bounswe/bounswe2024group11/wiki/Sequence-Diagrams).

**Comment by ceydanursen** [comment]
Sequence diagrams for quiz creation, forum question creation, semantic search for forum and a generic sequence used in other seqeunces are added [here](https://github.com/bounswe/bounswe2024group11/wiki/Sequence-Diagrams).

**Comment by MucahitErdoganUnlu** [comment]
added sequence diagram for semantic search for quizzes as well

**Comment by meminciftci** [comment]
Added sequence diagrams for [blocking](https://github.com/bounswe/bounswe2024group11/wiki/Sequence-Diagrams#block-user) and [following](https://github.com/bounswe/bounswe2024group11/wiki/Sequence-Diagrams#block-user) another user.

**Comment by ArdaVural** [comment]
Added sequence diagram for bookmarking questions. I need review @meminciftci .

**Comment by meminciftci** [comment]
> Added sequence diagram for bookmarking questions. I need review @meminciftci .

It looks good. Good job.

**Comment by ozankrkya** [comment]
Added sequence diagram for take quiz. I think it's better to review it @MucahitErdoganUnlu.
