### ISSUE TITLE
Bootstrap Mobile Application

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#524]
# 🧱 Description

The project's mobile application will be developed with React Native. The mobile application should be initialized so that further developments can be made on top of it.

## 📋 Acceptance Criteria

- [x] We have a bootstrap mobile application in the repo.
- [x] We run the mobile application on both an Android emulator and an iOS simulator.

**Comment by Meminseeker** [comment]
This [video](https://www.youtube.com/watch?v=9vydY9SDtAo) is useful for both initializing the mobile application and implementing a JWT-based authentication with React Native.

**Comment by Meminseeker** [comment]
We've worked on this issue with @yunuskaydin 

The PR #522 is the proof of work.

**Comment by yunuskaydin** [comment]
This issue can be closed as its PR #522 is merged and closed.
