### ISSUE TITLE
Implement JWT-based authentication system for Mobile application

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#525]
# 🧱 Description

The authentication mechanism for the project is JWT-based. So, the mobile application needs to handle JWT-based authentication. It should have register, login, and logout features accordingly.

## 📋 Acceptance Criteria

- [x] We have a JWT-based registration and login system in the mobile application.
- [x] The mobile application stores JWT tokens locally across sessions.
- [x] The mobile application is able to make API calls with stored tokens.

**Comment by Meminseeker** [comment]
We've developed the Auth context and required features stated in the description with @yunuskaydin. 

You can check the repository at the [commit](https://github.com/bounswe/bounswe2024group11/tree/d91fb6ad4d977edd9af4e3350c9a11d4da798901) in `feat/mobile-authcontext` branch.

**Comment by yunuskaydin** [comment]
This issue can be closed as its PR #523 is merged and closed.
