### ISSUE TITLE
Create the Initial Database Schema

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#529]
# 🧱 Description

We need to decide which relational database to use in our project. Additionally, database configuration should be done in the settings.py and updated in .env files. 

## 📋 Acceptance Criteria

- [x] A relational schema is ready and connected to the backend.
- [x] Dockerized application contains its mounted database.

**Comment by ozankrkya** [comment]
We have decided to use mysql server for our db container. Docker Compose will include mysql image as db service.

**Comment by ozankrkya** [comment]
- We have mounted mysql v8.0 as database in our django backend application. 
- Docker-Compose pulls this image and makes necessary configurations on it.
