### ISSUE TITLE
Research Forgot Password Feature for Django

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#533]
# 🧱 Description
It is necessary to research and decide if implementing "forgot password" feature in Django is feasible in our project's lifetime.
## 📋 Acceptance Criteria

- [ ] A good understanding of the implementation should be presented.

**Comment by ozankrkya** [comment]
I am closing this issue since we have decided to implement forgot password feature. 
There will be another issue open for this including implementation.
