### ISSUE TITLE
Implement Forgot Password Feature

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#534]
# 🧱 Description

- Reset Password functionality should be added into the login/registration system.
- A research shall be made to decide to use which structure to use.
- Implementation should be done and tested before going live.
## 📋 Acceptance Criteria

- [ ] Research is done about feature implementation. Structure to be used is decided.
- [ ] Reset Password feature is implemented on backend.

**Comment by umitcan07** [comment]
we're not doing this feature due to time limitations
