### ISSUE TITLE
Document the Lab Meeting #4

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#536]
# 🧱 Description

The meeting notes for Lab Meeting 4 should be documented.

## 📋 Acceptance Criteria

- [ ] Lab Meeting 4 meeting notes are documented

**Comment by meminciftci** [comment]
Initial draft can be reached from [here](https://github.com/bounswe/bounswe2024group11/wiki/Lab-Meeting-%234)

**Comment by yunuskaydin** [comment]
It looks clean and complete, good job.
