### ISSUE TITLE
Implement Forum Interface and Components for Mobile application

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#537]
# 🧱 Description

#### To be reviewed by: @Meminseeker 
The mobile application has to contain forum question and answer components based on proper UI's in order to present at the Customer Milestone 1.
## 📋 Acceptance Criteria

- [x] The mobile application has a proper UI.
- [x] The mobile application has forum question component.
- [x] The mobile application has answer component.

**Comment by meminciftci** [comment]
I think this task is already done. If it is, can you close it? @Meminseeker @yunuskaydin
