### ISSUE TITLE
Dockerize & Deploy The Application

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#538]
# 🧱 Description

#### We have created 2 staged plan for our deployment process.
1. Our application will be deployed an AWS EC2 instance. Once we created our containers for different services, we will push them to ECR and compose them on our EC2 instance.
2. Automated workflows of Github Actions will be utilized in a way they will be triggered with pushes on specified branches and update related containers in ECR.
3. If process is not completed by October 19, we will utilize DigitalOcean droplet service which will pull our repo into its instance and build&run on it for deployment.

## 📋 Acceptance Criteria

- [x] Local Deployment Files are ready on repository, Dockerfile for backend, client and Docker-Compose file for build.
- [ ] Deployment files for automation workflow are ready on repository.
- [ ] Workflow files are ready on repository.
- [x] Application is up running on both development and production servers.

**Comment by meminciftci** [comment]
Thank you for your detailed explanation. @ozankrkya 

I will be closely tracking your progress on this manner. 

Also, it would be a good idea to set additional deadlines for each subtask. You do not need to mention them here, but it would be good to keep that in mind.

**Comment by ozankrkya** [comment]
We have completed the first step in the description of the issue, October 19.

**Comment by meminciftci** [comment]
This issue is partially completed. I am closing it.
