### ISSUE TITLE
List the example domains for our project

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#54]
# 🧱 Description

We need to have several domain ideas to discuss and decide

## 📋 Acceptance Criteria

- [x] There are at least 8 different domain ideas to discuss within a team

**Comment by ozankrkya** [comment]
We have decided on our domain to work on (as chess) in [11 March Meeting](https://github.com/bounswe/bounswe2024group11/wiki/Meeting-%235), thus I am closing this issue.

**Comment by umitcan07** [comment]
We have entertained different ideas and settled on "Comics" as our domain. So this is complete and irrelevant.

**Comment by uskudarli** [comment]
Irrelevant? Why?

**Comment by umitcan07** [comment]
@uskudarli This issue was to bring up ideas, as we have done in our communication media, calls and Github. And we have settled on a topic. Probably my wording wasn't up to a good standard. I mean now that we have a domain, listing out new domains is not necessary.
