### ISSUE TITLE
Implement Vote Endpoints for Forum Questions

### ISSUE THREAD

**Issue by ArdaVural** [bounswe/bounswe2024group11#543]
# 🧱 Description

We need to implement the API endpoints for upvote and downvote forum questions. These endpoints will allow registered users to upvote or downvote questions from the forum. Unit tests should be provided. Swagger docs should be documented.

## 📋 Acceptance Criteria

- [x] Voting forum question endpoint is implemented.
- [ ] Swagger is documented.
- [ ] Unit tests are implemented.

**Comment by ArdaVural** [comment]
Instead of 2 endpoints as UpVote and DownVote, we have decided to implement 1 endpoint which covers both UpVote and DownVote endpoints, called Vote.
Changed the issue according to this.

**Comment by meminciftci** [comment]
The task is done in another issue. See #640
