### ISSUE TITLE
Create Mock Quiz Data For Clientside

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#559]
# 🧱 Description

## 📋 Acceptance Criteria

- [x] A mock quiz is created for each type of quiz
- [x] 50 quiz data are created for to show in quiz feed.

**Comment by meminciftci** [comment]
Additional to data created by Hasan Kerem for mock quizzes, I also provided several data examples. We can close this issue if Ümit also approves the current state.

@umitcan07

**Comment by meminciftci** [comment]
I think this issue is completed. I am closing it.
