### ISSUE TITLE
Add a Branded Error Page to Client App

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#562]
# 🧱 Description

When an error is thrown from the client app, react router catches it and renders a default/generic error page. We should replace it for better UX and DX.

## 📋 Acceptance Criteria

- [x] The default error component by the `react router` is replaced something similar to the overall theme of the app with a friendly description as well as relevant aria attributes.

**Comment by hks1444** [comment]
The new error page looks good.
