### ISSUE TITLE
Find and Use a Container Registry

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#564]
# 🧱 Description

A container registry such as Docker Hub is necessary to push, host, and pull Docker images. Decide which platform to use, and then push your images to it.

## 📋 Acceptance Criteria

- [x] We have decided on the container registry platform.
- [x] We have the Docker images pushed to the registry.

**Comment by meminciftci** [comment]
Docker Hub is chosen for mentioned purposes. Closing the issue...
