### ISSUE TITLE
Decide on Deployment Plan

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#565]
# 🧱 Description

Every deployment process should have a planned process. Consider alternative processes for this project and decide on one.

## 📋 Acceptance Criteria

- [x] We have decided on our deployment process.
- [x] We have explained our deployment process in the wiki.

**Comment by meminciftci** [comment]
Deployment process is discussed and decided. The only thing remaining is creating a wiki page that explains this procedure.

**Comment by ozankrkya** [comment]
We executed the deployment procedure for milestone 1 according to our plan we have developed under this issue.
