### ISSUE TITLE
Setup AWS for Deployment

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#566]
# 🧱 Description

We decided to use AWS (Amazon Web Services) as a compute service provider for our deployment plan. Create a new account there and adjust settings and credentials.

## 📋 Acceptance Criteria

- [x] We have an AWS account dedicated to this class.
- [x] We have a suitable IAM user for the project.
- [x] We have AWS CLI configured on our local devices.
- [x] We have an EC2 instance and related configurations (e.g., VPC security groups) set up.
- [x] We have validated to make SSH connections to our EC2 instance.

**Comment by ozankrkya** [comment]
We have completed all of the steps above securely.
