### ISSUE TITLE
Configure a CI/CD Pipeline for Dev Environment Utilizing GitHub Actions

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#568]
# 🧱 Description

After the first manual deployment, the deployment process can be automated.

## 📋 Acceptance Criteria

- [x] We have a CI/CD workflow for the dev environment defined in the repo.
- [ ] We have deployment secrets defined for the GitHub Actions.
- [ ] We have validated our CI/CD pipeline is working for the dev environment.

**Comment by meminciftci** [comment]
This issue is not relevant anymore. Closing it.
