### ISSUE TITLE
Fix Network Refuses to Connect for Backend Application Error in the Deployed Dev Environment

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#569]
# 🧱 Description

The application is deployed to the dev environment, and the services are running. However, the backend application is not reachable from both browsers and Postman. Fix this issue

## 📋 Acceptance Criteria

- [x] Our deployed backend application is reachable from the Internet.

**Comment by meminciftci** [comment]
I believe this is fixed. Closing the issue.
