### ISSUE TITLE
Enhance Forum Feed page

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#575]
# 🧱 Description

The initial forum feed page is quickly implemented with the help of generative AI tools. It is needed to make it comply with the UI/UX designs. By adding new UI components and fixing old ones, enhance the forum feed screen.

## 📋 Acceptance Criteria

- [x] We have a forum feed screen similar to the UI/UX designs made.

**Comment by meminciftci** [comment]
This task has been already done. Closing it.
