### ISSUE TITLE
Implement Leaderboard Screens for Mobile Application

### ISSUE THREAD

**Issue by yunuskaydin** [bounswe/bounswe2024group11#598]
# 🧱 Description

#### To be reviewed by: @Meminseeker 
The mobile application has to have proper leaderboard screens with proper UI's.
## 📋 Acceptance Criteria

- [x] The mobile application has a proper quiz leaderboard screen.
- [x] The mobile application has a proper forum leaderboard screen.

**Comment by Meminseeker** [comment]
You may look at the related [web page](http://54.247.125.93/leaderboard)

**Comment by yunuskaydin** [comment]
Mobile app has a proper leaderboard screen for forum and quiz.
