### ISSUE TITLE
Fix Radio Button for Quiz Sorting (W3C ARIA)

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#599]
# 🧱 Description
In client service, radio buttons for sorting quiz feed under Quizzes tab is not accessible with ARIA standart. Tab presses skips over radio buttons for sorting.
## 🛣️ Reproduction
Enabling radio buttons by changing their attributes should resolve this problem. 

## 📋 Acceptance Criteria

- [x] Quiz Feed Sorting buttons are accessible according to ARIA standart.

**Comment by umitcan07** [comment]
good job @hks1444
