### ISSUE TITLE
Document SVG 2 Standards

### ISSUE THREAD

**Issue by ArdaVural** [bounswe/bounswe2024group11#600]
# 🧱 Description
Create documentation that summarizes the Scalable Vector Graphics (SVG) 2 standards, focusing on new features, compatibility, and best practices for using SVGs in modern web development.

## 📋 Acceptance Criteria

- [x] Comprehensive overview of SVG 2 is documented.
- [ ] Additional resources and links to official SVG 2 documentation are included.

**Comment by meminciftci** [comment]
Svg example is added. It can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Standards:-SVG-2-Accessibility-Standards).

**Comment by umitcan07** [comment]
thanks for adding the bottom disclaimer :) 
we need standards AND design sophistication
