### ISSUE TITLE
Implement Quiz Screens for Mobile

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#601]
# 🧱 Description

The mobile application must have screens for quizzes. Implement them.
Please note that this issue may have multiple sub-issues.

## 📋 Acceptance Criteria

- [x] Mobile app has a quiz-feed screen
- [x] Mobile app has a quiz-detail screen
- [x] Mobile app has a quiz-taking screen
- [x] Mobile app has a quiz-reviewing screen

**Comment by meminciftci** [comment]
Is this task done? Are there any additions you are going to make? @yunuskaydin @Meminseeker
