### ISSUE TITLE
Add Detailed Error Messages to Swagger Documentation

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#605]
# 🧱 Description
To improve developer experience and make the API more user-friendly, we should add detailed error messages to the Swagger documentation. These error messages should include HTTP status codes, descriptions of possible errors, and any relevant error fields.

## 📋 Acceptance Criteria

- [ ] Each endpoint should list the relevant error messages and HTTP status codes.

**Comment by MucahitErdoganUnlu** [comment]
This issue still persists. In addition to this, we need to provide more detailed descriptions and more meaningful example values
