### ISSUE TITLE
Fix Svg Accessibility 

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#606]
# 🧱 Description

Our current logo SVG component does not make use of accessible tags and attributes. Make sure to either flag it as role image or add relevant attributes.

## 🛣️ Reproduction

- Navigate to any page with Turquiz logo

## 📋 Acceptance Criteria

- [x] Logo component has either role as image or role description (aria-label, aria-labelledby)

**Comment by umitcan07** [comment]
fixed it with the branch

**Comment by meminciftci** [comment]
Good job
