### ISSUE TITLE
Update the personal effort page 

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#62]
# 🧱 Description

Update the information written on [Personal Effort (Muhammet Emin Çiftçi)](https://github.com/bounswe/bounswe2024group11/wiki/Personal-Effort-(Muhammet-Emin-%C3%87ift%C3%A7i)).

## 📋 Acceptance Criteria

- [ ] The information about the personal effort of Muhammet Emin Çiftçi is stored to the current date.

**Comment by meminciftci** [comment]
The personal efforts page have been updated: [Personal Effort (Muhammet Emin Çiftçi)](https://github.com/bounswe/bounswe2024group11/wiki/Personal-Effort-(Muhammet-Emin-%C3%87ift%C3%A7i))

**Comment by umitcan07** [comment]
Can you include your name in the title to avoid any confusion?
