### ISSUE TITLE
Document Meeting Notes Lab Meeting #6

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#620]
# 🧱 Description

The things done in the sixth lab needs to be documented.

## 📋 Acceptance Criteria

- [x] The meeting notes are well documented.

**Comment by meminciftci** [comment]
The initial version is [here](https://github.com/bounswe/bounswe2024group11/wiki/Lab-Meeting-%236)

**Comment by yunuskaydin** [comment]
Notes are well structured, I'm closing this issue.
