### ISSUE TITLE
Create user scenarios

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#63]
# 🧱 Description

We must create the scenarios and write them down to the wiki page. It is better to review other projects and their scenarios to create ours.

## 📋 Acceptance Criteria

- [x] Five use case scenarios are created according to assignment.

**Comment by umitcan07** [comment]
@Meminseeker and I reviewed the scenarios and entertained the ways we can create flows.
We have also spotted a few weaknesses in our scenarios.

Here are the suggested flows:

### Emily  
Search Posts ➡️ Scroll Through Posts ➡️ People Who Liked The Posts ➡️ Sees Yet Another Friend ➡️ Register ➡️ Account Settings ➡️ Delete Account  

### Jack  
Log In ➡️ Search ➡️ Bookmark ➡️ Bookmark ➡️ Log Out  

### Hasan  
Edit My Profile ➡️ See Followers ➡️ Follow ➡️ See Following ➡️ Profile ➡️ Unfollow  

### Kaito  
Sees a Post in Feed ➡️ Like ➡️ Comment ➡️ Reply ➡️ New Post (Image)  

### Jeff  
New Post (Text) ➡️ Edit ➡️ See a Comment ➡️ Delete Post

**Comment by ceydanursen** [comment]
Five scenarios are created accordingly : 

[Scenario 1](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-1)

 [Scenario 2](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-2)

[Scenario 3](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-3)

[Scenario 4](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-4)

[Scenario 5](https://github.com/bounswe/bounswe2024group11/wiki/Scenario-5)

**Comment by Meminseeker** [comment]
Please, be aware that there are some changes in the scenarios @ceydanursen . Each scenario should be modified according to the flows @umitcan07 shared above.

**Comment by hks1444** [comment]
I have updated the scenarios as you requested. Feel free to change them if you see any mistake.

**Comment by tenacke** [comment]
It looks nice! Well done!

**Comment by Meminseeker** [comment]
It seems pretty good. I also added mock-up screens below them. You can check it [here](https://github.com/bounswe/bounswe2024group11/issues/68#issue-2189394019).
