### ISSUE TITLE
Learn SparQL for querying WikiData (Ümit Can Evleksiz)

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#65]
# 🧱 Description

Learn SPARQL from [this link](https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial)

## 📋 Acceptance Criteria

- [x] Being capable of writing basic queries.
- [x] There are a few examples written in the [SparQL research template](https://github.com/bounswe/bounswe2024group11/wiki/SPARQL) by the assignee.

**Comment by umitcan07** [comment]
I have added the fundamentals in the [research page](https://github.com/bounswe/bounswe2024group11/wiki/SPARQL)
I will add example query and results now

**Comment by umitcan07** [comment]
Open for reviews now @Meminseeker

**Comment by Meminseeker** [comment]
I reviewed your research page. Good job!

**Comment by Meminseeker** [comment]
Please update your issue title by adding your name, so that we can differentiate it from other SPARQL issues.

**Comment by umitcan07** [comment]
@Meminseeker Good one, thanks
