### ISSUE TITLE
Resolve CORS Problem for Client-Backend Connection

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#651]
# 🧱 Description
- In the current implementation of backend service, there is no CORS configuration. 
- In order to connect client service to backend service to display features in the Milestone 2 Demo, this has to be resolved. 
## 📋 Acceptance Criteria

- [x] `settings.py` file should be updated so that it includes necessary configurations for CORS headers.
- [x] `requirements.txt` file should include related application installation.

**Comment by meminciftci** [comment]
The tasks mentioned in this issue had successfully done.
