### ISSUE TITLE
Implement Viewing the Score of a User For a Quiz

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#652]
# 🧱 Description
We have imlpemented TakeQuiz ModelViewset where a user can answer questions of a quiz and review his answers. We now need to implement a function to calculate and return the score of the user according to his correct answers. Update unit tests for TakeQuiz to view the score.
## 📋 Acceptance Criteria

- [ ] The user can view his score after taking a quiz.
- [ ] Unit tests are updated for TakeQuiz accordingly.

**Comment by MucahitErdoganUnlu** [comment]
We implemented this before, but seems broken. Always returns 0

**Comment by meminciftci** [comment]
What is the current state of this issue? Is it solved? 
@MucahitErdoganUnlu

**Comment by meminciftci** [comment]
The issue is now complete.
