### ISSUE TITLE
Change interaction fields with forum questions to ID's

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#655]
# 🧱 Description
We implemented interaction fields (is_upvoted, is_downvoted and is_bookmarked) as boolean fields for forum questions. However, when the user wants to delete his interaction (upvote, downvote, bookmark), he has no access to id of his interaction, so he cannot delete. Therefore, we need to change this field from bool to interaction_id. Update unit tests accordingly.
## 📋 Acceptance Criteria

- [x] Make the change for bookmark
- [x] Update bookmark unit tests
- [x] Make the change for upvote
- [x] Update upvote unit tests
- [x] Make the change for downvote
- [x] Update downvote unit tests

**Comment by MucahitErdoganUnlu** [comment]
Ümit is currently working on the issue. you can follow his branch if you want

**Comment by meminciftci** [comment]
This task has already done. Closing the issue.
