### ISSUE TITLE
Implement Forum Pagination On ClientSide

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#675]
# 🧱 Description

## 📋 Acceptance Criteria

- [ ] Forum Pagination is implemented on the client.

**Comment by hks1444** [comment]
Implemented on [this pr](https://github.com/bounswe/bounswe2024group11/pull/680/commits/f8bae35be674a98ad50572297a8155f17f5e27cb) which contains client/src/hooks/pagination.ts file.

**Comment by umitcan07** [comment]
we haven't adopted this. closing
