### ISSUE TITLE
Implement Profile Enpoint for Authenticated Users

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#681]
# 🧱 Description

A new endpoint is required to manage user profile data in the application. This endpoint should allow authenticated users to retrieve and update their profile information. The profile should include details such as the user's name, email, avatar, and other relevant fields.

## 📋 Acceptance Criteria

- [x] Authenticated users can retrieve their profile data using a GET request.
- [x] Authenticated users can update their profile using a PATCH request.
- [x] Tests are written and pass for all scenarios.
- [x] Swagger documentation is available for the endpoint.

**Comment by ceydanursen** [comment]
I have implemented profile page (serializers and views). After working with Ozan, we decided to use user_id for delete profile.

**Comment by ceydanursen** [comment]
Also some extra checks to ensure only the user can delete his/her profile should be added.

**Comment by meminciftci** [comment]
This task seems complete. Closing it.
