### ISSUE TITLE
Create Overall Project Plan

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#72]
# 🧱 Description

Overall scheme of project plan needs to be done. Distribution of project's general tasks to three months from now on should be completed.

## 📋 Acceptance Criteria

- [ ] We have a Project Libre project displaying project plan.
- [ ] Relations between tasks and Gantt charts are prepared.

**Comment by meminciftci** [comment]
The overall project plan has been done and it has been documented: [Project Plan](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan)
