### ISSUE TITLE
Implement Quiz Creation

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#728]
# 🧱 Description

Implement Quiz Creation feature on web. These points should be taken care of:
* A question text is fetched from `tagging` endpoint
* There are 3 types of quizzes. In type 1 and type 2, the `get-translation` endpoint is used to get the correct answer automatically. In type 3, the correct answer will be fetched from the same `tagging` endpoint.
* While creating a question, hint endpoint will return definitions, examples, images etc. Users can type custom hint text. Users also can upload image as hint.
* Backend supports more than one hint. If you want, you can implement multiple hints for one question.

**Comment by umitcan07** [comment]
this has been "the work" of this milestone by a far margin. with all aspects :) 

![CleanShot 2024-12-20 at 16 02 10@2x](https://github.com/user-attachments/assets/7fb698e7-1a53-4c51-bf4a-6e1aa53e1c4f)


![CleanShot 2024-12-20 at 16 02 20@2x](https://github.com/user-attachments/assets/d6ab1066-d8cb-4712-8db1-10041add5263)

![CleanShot 2024-12-20 at 16 02 23@2x](https://github.com/user-attachments/assets/302dab49-71dc-4245-a579-fb42ec5f0bd9)
