### ISSUE TITLE
Add New Sub-Features to Profile

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#729]
# 🧱 Description
Description
Enhance the profile functionality by adding the following sub-features:

1- English Proficiency Selection:

> Allow users to select their English proficiency level (e.g., Beginner, Intermediate, Advanced) during registration.

2- Badges:

> Introduce a badge system to recognize user achievements.
> Example badges:
> Quiz Master: For completing 10 quizzes with 80%+ accuracy.
> Forum Contributor: For posting or replying to 20 forum questions.
> Display badges in the user profile.

3- Follow System:

> Enable users to follow other users.
> Show the list of followers and following users in the profile.
> Include counts of followers and following in the profile summary.

## 📋 Acceptance Criteria

- [x] Users should see the proficiency level they selected for themselves.
- [x] A badge mechanism should be implemented fundemantally.
- [x] The user interactions (follower users and followed users) can be seen at the profile page.

**Comment by umitcan07** [comment]
We've discussed with @MucahitErdoganUnlu and @Meminseeker to finalize this ideas.
