### ISSUE TITLE
Quiz Freeze and Replace Feature Scopping.

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#730]
# 🧱 Description

As per the request from Suzan Hoca, we should allow users to give feedbacks about quizzes, potentially the ones with many typos and illy formatted questions. We should decide what to do and in what ways about this feedback - quiz edit mechanism 

## 📋 Acceptance Criteria

- [x] Decide what to do about editing quizzes
- [x] Decide what to do about giving feedback to quizzes.

**Comment by umitcan07** [comment]
- Feedbacks will be displayed to the only creator
- Creators will see a page similar to a quiz review with questions and answers as well the feedbacks. There will be options to edit, freeze, and delete.
- In case of a freeze or delete, the points gained will not be subtracted from the users.
