### ISSUE TITLE
Enrich Profile Model to Include Customisation and Gamification

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#740]
# 🧱 Description

We should store the proficiency, the badges earned and the topics they are interested to implement customisation and gamification features.

Blocked by #727 

## 📋 Acceptance Criteria

- [x] A user model has fields for proficiency, badges earned and the interested topics (linked data)

**Comment by ceydanursen** [comment]
Related issue: #795

**Comment by umitcan07** [comment]
We've implemented the relevant fields to the profile. :)
