### ISSUE TITLE
Implement Get Achievements Endpoint

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#756]
# 🧱 Description
Users gain achievements over time. We have Achievements model on Django. We have UserAchievemnets model which stores which user acquired which achievment. We need to implement an endpoint that returns all the achievements together with the information for each achivement whether the current user has acquired it.

Branch name shall be commented for better communication

**Comment by ceydanursen** [comment]
achievement is the branch name for the endpoint implementation

**Comment by MucahitErdoganUnlu** [comment]
We need to return a list of all of the achievements. In additipn to the fields of an achievement, each achievement should include a field that indicates if the user earned it, and if so at what time
