### ISSUE TITLE
Implement Interests CD Endpoints

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#767]
# 🧱 Description
We have interests for a user that can be seen in the `interests` field in the CustomUser model. We need to implement POST and DELETE methods that creates or deletes an interest instance of a user. These methods should only allow the user to delete only its own interest. You can also inspect the `interests` array that is returned with `profile` endpoint. An example `interests` array from the profile endpoint: 
```
{
  "id": 4,
  "email": "elonmusk@email.com",
  "full_name": "elonmusk",
  "avatar": "https://api.dicebear.com/9.x/avataaars/webp?accessories=eyepatch,kurt,prescription01&seed=Jason%20Lee",
  "quizzes_taken": [
    {
      "id": 1,
      "quiz": 1,
      "user": 4,
      "date": "2024-12-11T19:48:48.386937Z",
      "answers": [],
      "score": 0,
      "correct_answer_count": 0,
      "wrong_answer_count": 0,
      "empty_answer_count": 0
    }
  ],
  "bookmarked_forums": [],
  "score": 0,
  "achievements": [],
  "interests": [
    {
      "id": 10,
      "name": "string",
      "linked_data_id": "bn:1498288n",
      "description": "string"
    },
    {
      "id": 11,
      "name": "string",
      "linked_data_id": "bn:198288n",
      "description": "string"
    }
  ]
}
```

#### To be reviewed by: @MucahitErdoganUnlu

**Comment by ceydanursen** [comment]
I have added the required interest for users. Impelemented post and delete views and swagger documentation.
