### ISSUE TITLE
Switch Views on Forum Images

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#768]
# 🧱 Description

Currently we use `object-cover` to display images, for a better visibility and UX, users should be able to switch between `cover` and `contain` modes. Use tailwind classes with cva.

blocked by #739 

## 📋 Acceptance Criteria

- [x] Pressing on an image chnages the way it is displayed as an object: `cover` and `fit`

**Comment by hks1444** [comment]
This implemented [here](https://github.com/bounswe/bounswe2024group11/pull/779). Can you close this issue?

**Comment by umitcan07** [comment]
:) gj
