### ISSUE TITLE
Implement Forum Question Image Features On Mobile

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#778]
# 🧱 Description
The image upload and displaying features are implemented on the web frontend and connected to the backend. To create consistent UX, the mobile team should at least implement displaying image on forum question images. It would be better if the mobile team also implemented the image upload feature for the forum question creation.

## 📋 Acceptance Criteria

- [ ] The mobile app can display forum question image.
- [ ] The mobile app allows uploading image while creating new forum question. (Optional)

**Comment by yunuskaydin** [comment]
discarded due to lack of time.
