### ISSUE TITLE
Introduce Zustand for Quiz Creation Process

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#780]
# 🧱 Description

Using React State is going to be A HELL managing all of the internal intricacies of a draft question as well as dealing with the user interactions and validations.

Import `zustand` and use a QuizCreate type of store to keep track of global changes across the pages of quiz creation

## 📋 Acceptance Criteria

- [x] Use global zustand store for quiz creation pages

**Comment by hks1444** [comment]
You did a fantastic job. Zustand allows us to manage states cleanly. In this way, the implementation of the quiz creation will be cleaner and less error-prone.
