### ISSUE TITLE
Score field in Profile is always zero

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#789]
# 🧱 Description
Score field in the profile is supposed to increase when a user gains a point from a quiz. In other words, we write this value to the user's model. However, in the current situation, it is always zero.
## 🛣️ Reproduction
1. solve a quiz as an authenticated user
2. Make a get request to the profile endpoint

You will see the score as zero

**Comment by ozankrkya** [comment]
#### I have tried to reproduce the bug.
- I have created new user (User A) in my local deployment environment on top of fixtures.
- I have created a quiz using the account of User A in the client service.
- Then, I have created another account (User B) and took the quiz created by User A.

#### There was no problem with points scored in profile in User B.
- I have checked the API with returned question and quiz points. All seems well. 
- However, in the data loaded by fixtures, quizzes doesn't have points since they are not submitting question points during the creation of fixtures.

**Comment by ozankrkya** [comment]
#### Music Production Quiz Created by user `@speedy` (User A)
<img width="1453" alt="Screenshot 2024-12-15 at 11 27 58" src="https://github.com/user-attachments/assets/922fc105-2011-4ebf-ade6-6335a46af4d5" />

#### Music Production Quiz Attempted by user `@ozi` (User B) - 50 points scored in profile.
<img width="1464" alt="Screenshot 2024-12-15 at 11 29 22" src="https://github.com/user-attachments/assets/7f6fe04a-6b99-4886-94e7-97fc11bb1c59" />

#### Below you can see the data for Music Production Quiz in my local deployment environment

{
   "id": 3,
   "title": "Music Production",
   "description": "Includes vocabulary for key terms about electronic music production.",
   "difficulty": 3,
   "author": {
      "id": 8,
      "username": "speedy",
      "email": "sait@gmail.com",
      "full_name": "sait",
      "avatar": "https://api.dicebear.com/9.x/avataaars/webp?accessories=eyepatch,kurt,prescription01&seed=Douglas Sweeney",
      "is_followed": null,
      "is_blocked": null
   },
   "tags": [
      {
         "id": 8,
         "name": "production",
         "linked_data_id": "bn:00064590n",
         "description": "The act or process of producing something"
      }
   ],
   "type": 1,
   "created_at": "2024-12-15T08:00:47.168014Z",
   "questions": [
      {
         "id": 9,
         "question_text": "loop",
         "question_point": 20,
         "choices": [
            {
               "id": 33,
               "choice_text": "tempo",
               "is_correct": false
            },
            {
               "id": 34,
               "choice_text": "yapı",
               "is_correct": false
            },
            {
               "id": 35,
               "choice_text": "ton",
               "is_correct": false
            },
            {
               "id": 36,
               "choice_text": "döngü",
               "is_correct": true
            }
         ],
         "hints": []
      },
      {
         "id": 10,
         "question_text": "genre",
         "question_point": 30,
         "choices": [
            {
               "id": 37,
               "choice_text": "müzik tarzı",
               "is_correct": true
            },
            {
               "id": 38,
               "choice_text": "ton",
               "is_correct": false
            },
            {
               "id": 39,
               "choice_text": "ritim",
               "is_correct": false
            },
            {
               "id": 40,
               "choice_text": "tempo",
               "is_correct": false
            }
         ],
         "hints": []
      }
   ],
   "num_taken": 1,
   "is_taken": true,
   "rating": {
      "score": null,
      "count": 0
   },
   "is_my_quiz": false,
   "quiz_point": 50
}

**Comment by umitcan07** [comment]
great job guys!
