### ISSUE TITLE
Multiple Achievement Popover Overlap

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#798]
# 🧱 Description
The achievements popovers can overlap if the user hovers over them fastly. This can be seen in the following image:

![2eea3e01-07eb-49ea-a885-46e133c89307](https://github.com/user-attachments/assets/868a23e6-9004-4f39-8b0c-f3b3f698f6a9)

## 🛣️ Reproduction
- Open profile or achievements page 
- Hover over multiple achievements fastly

**Comment by umitcan07** [comment]
fixed as of the last main
