### ISSUE TITLE
Quiz Author Profile Redirection

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#802]
# 🧱 Description

![CleanShot 2024-12-14 at 18 56 11@2x](https://github.com/user-attachments/assets/f3d03d86-4f1c-4925-b60b-4b60a8b65dc4)

## 🛣️ Reproduction

- Open `/quizzes`
- Click on a username 
- It won't redirect you to the profile

## 📋 Acceptance Criteria

- [ ] The author links should redirect to the relevant profile route.

**Comment by hks1444** [comment]
We need to remove hovercard it is too buggy.

**Comment by umitcan07** [comment]
@hks1444 the bug on the hovercard should've been gone by now!

**Comment by umitcan07** [comment]
in either case this issue is completed.
