### ISSUE TITLE
Return Full Forum Questions From Backend Profile Endpoint 

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#811]
# 🧱 Description
Currently profile/{username}/ endpoint does not return all data of the bookmarked forum questions. The data returned for the bookmarked post is not enough to display them on the bookmarked post section of the profile page. It must return all data of the bookmarked posts.

## 🛣️ Reproduction
- send request to profile/{username}/ endpoint

## 📋 Acceptance Criteria

- [ ] profile/{username}/ endpoint returns all data for the bookmarked forum questions.

**Comment by MucahitErdoganUnlu** [comment]
implemented #819
