### ISSUE TITLE
Return Full Quizzes Taken From Backend Profile Endpoint

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#814]
# 🧱 Description
Currently profile/{username}/ endpoint does not return all data of the taken quizzes. The data returned for the taken quizzes is not enough to display them on the quizzes taken section of the profile page. It must return all data of the taken quizzes.

## 🛣️ Reproduction

- send request to profile/{username}/ endpoint

## 📋 Acceptance Criteria

- [ ]  profile/{username}/ endpoint returns all data for the taken quizzes.

**Comment by ceydanursen** [comment]
We have fıxed the problem accordingly to return the details of the quizzes.

**Comment by MucahitErdoganUnlu** [comment]
implemented #819
