### ISSUE TITLE
Create and Document Testing Strategies

### ISSUE THREAD

**Issue by ArdaVural** [bounswe/bounswe2024group11#818]
# 🧱 Description

Define and document the testing strategies for the project to ensure comprehensive quality assurance. The strategies cover general testing approaches, backend testing (unit, integration, and end-to-end), mobile and web testing .  Provide example test results to validate the implementation.

## 📋 Acceptance Criteria

- [x] General testing strategies are documented.
- [x] Backend testing includes unit, integration, and end-to-end tests.
- [x] Web and mobile testing includes unit, integration, and end-to-end tests.
- [x] Example test results are provided.

**Comment by ArdaVural** [comment]
Necessary documents are created [here.](https://github.com/bounswe/bounswe2024group11/wiki/Testing-Strategiesurl) . 
@yunuskaydin

**Comment by yunuskaydin** [comment]
Document is created parallel with acceptance criterias.
