### ISSUE TITLE
Filter Hints to Deduplicate Before Sending

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#820]
# 🧱 Description

![CleanShot 2024-12-14 at 22 42 39@2x](https://github.com/user-attachments/assets/8f26da11-913a-4880-a63c-2761eaad6d3c)

We should not return with duplicate entries in the hint arrays.

## 📋 Acceptance Criteria

- [ ] No duplicate entries are responded from the server

**Comment by MucahitErdoganUnlu** [comment]
done 415de6f485663362c0947c79e596bb031ad60a94
