### ISSUE TITLE
Respons with Empty Array of Relevant Questions When Error Fetching Babelnet

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#823]
# 🧱 Description

## 🛣️ Reproduction
* Create a forum question with empty tags.
* go to detail of that forum question
* babelnet error occurs

**Comment by MucahitErdoganUnlu** [comment]
encapsulated babelnet helper call with try-except 514221a103488ad5a277ce60ef4f60d7b2e2f72a
