### ISSUE TITLE
Update Ümit's Personal Efforts Page

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#83]
# 🧱 Description

Update Ümit's personal efforts page so that it follows the rules presented in Customer Milestone 1.

### Examples: 
Poor examples: "I attended the lectures and group meetings" or "I designed a project plan".
Good example: "Researched the Swagger API Development support tools with <X> (another team member) and prepared the infrastructure. The resulting API documentation can be seen at <URI> (URI of your API documentation). "

## 📋 Acceptance Criteria

- [x] Ümit's personal efforts page reflects the work done by him and abides by the rules.

**Comment by tenacke** [comment]
It seems nice, I think you forgot to close so I did it for you.
