### ISSUE TITLE
Unify Forum and Quiz Feed with Semantic Search

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#833]
# 🧱 **Description**

The `/forum-questions` and `/quizzes` endpoints should accept an optional `linked_data_id` parameter alongside pagination parameters. If `linked_data_id` is present and not null, the endpoints should query the BabelNet API and return the enriched data. If `linked_data_id` is not provided or is null, the endpoints should skip the BabelNet API query and only return the standard data.

### Notes:
- Ensure proper validation of `linked_data_id` to prevent unnecessary API calls.
- Maintain backward compatibility for requests without `linked_data_id`.
- Optimize the BabelNet API call to avoid performance bottlenecks.

---

### 1. **Parameter Handling**
- The `/forum-questions` and `/quizzes` endpoints should accept `linked_data_id` as an optional query parameter.
- Validate that `linked_data_id` is either null or a valid non-null value.

### 2. **BabelNet API Integration**
- The endpoints should query the BabelNet API **only** if `linked_data_id` is present and valid.
- Ensure the API call is optimized and does not impact endpoint performance significantly.

### 3. **Standard Data Handling**
- If `linked_data_id` is null or not provided, the endpoints should bypass the BabelNet API and return only standard data (e.g., forum questions or quizzes).

### 4. **Pagination**
- Ensure the endpoints still support pagination parameters (`page`, `limit`) correctly, whether or not `linked_data_id` is provided.

### 5. **Error Handling**
- Return meaningful error messages if:
  - `linked_data_id` is invalid or malformed.
  - The BabelNet API call fails (e.g., network issues, API errors).
- Fallback gracefully to standard data if the BabelNet query cannot be completed.

### 6. **Backward Compatibility**
- Requests without `linked_data_id` should continue to function as they did previously, with no changes to their behavior.

### 7. **Performance**
- Measure and ensure that adding `linked_data_id` and querying BabelNet does not introduce significant latency to the endpoints.
- Implement appropriate caching mechanisms for frequent BabelNet queries, if applicable.

### 8. **Documentation**
- Update API documentation to reflect the new `linked_data_id` parameter, including examples of valid and invalid requests.

### 9. **Testing**
- Write unit tests to validate `linked_data_id` logic.
- Write integration tests to ensure correct BabelNet API behavior.
- Write performance tests to ensure endpoints meet acceptable response times.

---

**Comment by MucahitErdoganUnlu** [comment]
moved 12198e7e04f72758fab6e7137525f5e5489080b0
