### ISSUE TITLE
Leaderboard Endpoint Returns Wrong Score

### ISSUE THREAD

**Issue by hks1444** [bounswe/bounswe2024group11#840]
# 🧱 Description
Leaderboard endpoint returns 0 score for every user. But it should return the users' score.
## 🛣️ Reproduction
- Send get request to leaderboard endpoint.
## 📋 Acceptance Criteria

- [ ] Leaderboard endpoint returns the users' scores correctly.

**Comment by MucahitErdoganUnlu** [comment]
fixed 530f85049c18533bf63a110ade02861c855089f1
