### ISSUE TITLE
correct answer translation turkish characters

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#846]
# 🧱 Description
![image](https://github.com/user-attachments/assets/699db41e-f3b2-4f7c-b4ef-28a193d925ae)

## 🛣️ Reproduction
1. create a quiz question with the word "heat"
2. the correct answer is viewed as "isı"

**Comment by umitcan07** [comment]
inspect the markup (html)

i dont think there's anything wrong on our side.

its how linked data came to us

**Comment by MucahitErdoganUnlu** [comment]
fixed dec4ede789d3e5317cafd526abd6b63f3c7a7858
