### ISSUE TITLE
Update RAM according to Ceydanur's responsibilities

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#86]
# 🧱 Description

The[ Responsibility Assignment Matrix (RAM)](https://github.com/bounswe/bounswe2024group11/wiki/Responsibility-Assignment-Matrix) should reflect [Ceydanur's Personal Efforts](https://github.com/bounswe/bounswe2024group11/wiki/Personal-Effort-(Ceydanur-%C5%9Een))

## 📋 Acceptance Criteria

- [x] RAM includes Ceydanur's work.

**Comment by MucahitErdoganUnlu** [comment]
Good job!
