### ISSUE TITLE
Set Proficiency On Profile

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#860]
# 🧱 Description

We need to let users update their proficiency level.

## 📋 Acceptance Criteria

- [x] Users can update their proficiency level from their profile page
- [x] There's a helpful link for users to evaluate their proficiency level objectively.

**Comment by umitcan07** [comment]
![CleanShot 2024-12-20 at 15 06 56@2x](https://github.com/user-attachments/assets/a4c22264-7e4b-446d-bdae-0b2596357711)

done

**Comment by hks1444** [comment]
Good job.
