### ISSUE TITLE
Learn SPARQL to query Wikidata (Emre Kılıç)

### ISSUE THREAD

**Issue by tenacke** [bounswe/bounswe2024group11#87]
# 🧱 Description

Learn SparQL using [SPARQL tutorial](https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial)

## 📋 Acceptance Criteria

- [x] Learned how to write basic queries.
- [x] The tutorial page is read carefully.

**Comment by tenacke** [comment]
Added example response, added order by and limit feature to the [wiki](https://github.com/bounswe/bounswe2024group11/wiki/SPARQL)

**Comment by umitcan07** [comment]
Reviewed the contribution, good job!
