### ISSUE TITLE
Implement Quiz Result Screen

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#888]
# 🧱 Description

The quiz result screen, which appears after solving a quiz, is a dummy page. Implement this page to demonstrate the statistics such as correct answer count, wrong answer count, the score obtained, etc.

## 📋 Acceptance Criteria

- [x] The quiz result screen demonstrates the correct, wrong, and empty answer count
- [x] The quiz result screen demonstrates the count of hints used
- [x] The quiz result screen demonstrates the score you got from the quiz

**Comment by yunuskaydin** [comment]
Quiz result screen is implemented and works well as it can be seen in this [PR](https://github.com/bounswe/bounswe2024group11/pull/890).
