### ISSUE TITLE
Incorporate Quiz Result Screen Interactions

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#889]
# 🧱 Description

The quiz result screen should have rating and feedback functionalities to allow users to give feedback about the quiz to both the quiz owner and other platform users.

## 📋 Acceptance Criteria

- [x] The quiz result screen should have a rating mechanism out of five
- [x] The quiz result screen should allow users to give a text-based feedback to the quiz owner

**Comment by yunuskaydin** [comment]
Quiz result screen interactions have been implemented and works well as it can be seen in this [PR](https://github.com/bounswe/bounswe2024group11/pull/890).
