### ISSUE TITLE
Populate Database Tags

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#892]
# 🧱 Description

Currently as users type and search for interests and add them to their interests or to quiz/forums we keep the relevant tag in the db. This table lets the application suggest new tags to different people. 

The data we have currently is very limited, in terms of the number of tags we have in the db. That means our suggestions aren't very well functioning. We should load more tags.

But we shouldnt do so by using the app, because that way we'd consume the free credits, and would be possible IP-banned for parsing the BabelNet.

## 📋 Acceptance Criteria

- [x] The prod application has at least 50 interest tags.

**Comment by umitcan07** [comment]
I've queried BabelNet (via parsing `/tagging/` endpoint) Thereby producing a local database of interest tags. Merged them with the ones from @MucahitErdoganUnlu  and handed it over to @ozankrkya. And @ozankrkya loaded the data to prod database

**Comment by umitcan07** [comment]
[12_quiz_3.json](https://github.com/user-attachments/files/18210598/12_quiz_3.json)

The fixture I've created

**Comment by umitcan07** [comment]
![CleanShot 2024-12-20 at 15 21 43@2x](https://github.com/user-attachments/assets/97ae5e2c-fae4-43c4-a13d-2db2cebb7dab)

There we have them. 100 tags

**Comment by yunuskaydin** [comment]
Tags are created in a well manner. Good job!
