### ISSUE TITLE
Populate Database Forum Questions

### ISSUE THREAD

**Issue by umitcan07** [bounswe/bounswe2024group11#893]
# 🧱 Description

As per the CM3 requirements, our application has at least 100 realistic forum questions. 

## 📋 Acceptance Criteria

- [x] Database has at least 100 forum questions and a few people following each other

**Comment by umitcan07** [comment]
![CleanShot 2024-12-20 at 15 13 36@2x](https://github.com/user-attachments/assets/4144eeb3-081f-4302-bf4e-99147bcfc887)

This has been done

**Comment by hks1444** [comment]
Well done.
