### ISSUE TITLE
Populate the New Release's Data

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#894]
# 🧱 Description
Newer version of the application will be released after feedbacks of the advisor. Newer release's data should be populated with the one already created.

## 📋 Acceptance Criteria

- [x] Data of the current running app will be dumped to a .json file.
- [x] New release have the populated data.

**Comment by umitcan07** [comment]
![CleanShot 2024-12-20 at 16 03 30@2x](https://github.com/user-attachments/assets/33a48879-2cfa-4b42-bdbc-904257fae614)


GJ @ozankrkya @MucahitErdoganUnlu
