### ISSUE TITLE
Document the Project Plan on Wiki

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#92]
# 🧱 Description

A page in our Wiki is necessary for explaining the project plan and its step.

## 📋 Acceptance Criteria

- [x] We have a documentation page contains details about the project plan.
- [x] Deadlines and tasks are explained in the documentation.

**Comment by ozankrkya** [comment]
All assignees created their parts in documentation page. Created wiki page is added to sidebar.

**Comment by meminciftci** [comment]
Documenting the project plan has finished: [Project Plan](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan)
