### ISSUE TITLE
Update Ceydanur's Personal Efforts Page

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#98]
# 🧱 Description

Update Ceydanur's personal efforts page so that it follows the rules presented in Customer Milestone 1.

Examples:
Poor examples: "I attended the lectures and group meetings" or "I designed a project plan".
Good example: "Researched the Swagger API Development support tools with (another team member) and prepared the infrastructure. The resulting API documentation can be seen at (URI of your API documentation). "

## 📋 Acceptance Criteria

- [x]  Ceydanur's personal efforts page reflects the work done by him and abides by the rules.

**Comment by ceydanursen** [comment]
I updated my personal efforts according to the given format. It can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Personal-Effort-(Ceydanur-%C5%9Een))

**Comment by Meminseeker** [comment]
Looks like you keep track of your efforts regularly (unlike me :)) Good job!
